import { NextRequest } from 'next/server'
import { err } from '@/lib/server-utils'
import { assertSafeRemoteUrl } from '@/lib/network-guards'

function getMetaContent(html: string, matcher: RegExp): string {
  return html.match(matcher)?.[1]?.trim() || ''
}

function absolutizeUrl(value: string, base: URL): string {
  if (!value) return ''

  try {
    return new URL(value, base).toString()
  } catch {
    return value
  }
}

export const runtime = 'nodejs'
export const maxDuration = 30

export async function POST(req: NextRequest) {
  const url = new URL(req.url)
  const action = url.searchParams.get('action') || 'meta-tags'

  try {
    const body = await req.json()
    const { input = '', options = {} } = body

    // ── Meta tag generator ──────────────────────────────────
    if (action === 'meta-tags') {
      const { title, description, keywords, url: pageUrl, author, type = 'website' } = options

      const t = (title || input.split('\n')[0] || 'Page Title').slice(0, 60)
      const d = (description || input.slice(0, 160) || 'Page description').slice(0, 160)
      const k = keywords || 'keyword1, keyword2, keyword3'
      const u = pageUrl || 'https://example.com'

      const tags = `<!-- Primary Meta Tags -->
<title>${t}</title>
<meta name="title" content="${t}" />
<meta name="description" content="${d}" />
<meta name="keywords" content="${k}" />
${author ? `<meta name="author" content="${author}" />` : ''}
<meta name="robots" content="index, follow" />
<meta name="language" content="English" />
<meta name="revisit-after" content="7 days" />
<link rel="canonical" href="${u}" />

<!-- Open Graph / Facebook -->
<meta property="og:type" content="${type}" />
<meta property="og:url" content="${u}" />
<meta property="og:title" content="${t}" />
<meta property="og:description" content="${d}" />
<meta property="og:image" content="${u}/og-image.jpg" />
<meta property="og:site_name" content="${t}" />

<!-- Twitter -->
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:url" content="${u}" />
<meta name="twitter:title" content="${t}" />
<meta name="twitter:description" content="${d}" />
<meta name="twitter:image" content="${u}/twitter-image.jpg" />

<!-- Schema.org -->
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "${type === 'article' ? 'Article' : 'WebPage'}",
  "url": "${u}",
  "name": "${t}",
  "description": "${d}"
}
</script>`

      const warnings: string[] = []
      if (t.length > 60) warnings.push('Title exceeds 60 characters')
      if (d.length > 160) warnings.push('Description exceeds 160 characters')
      if (d.length < 120) warnings.push('Description is short — aim for 120-160 characters')

      return Response.json({ tags, title: t, description: d, titleLength: t.length, descriptionLength: d.length, warnings })
    }

    // ── Keyword extractor ───────────────────────────────────
    if (action === 'keywords') {
      const stopWords = new Set([
        'the', 'a', 'an', 'and', 'or', 'but', 'in', 'on', 'at', 'to', 'for', 'of',
        'with', 'by', 'is', 'it', 'as', 'be', 'was', 'are', 'were', 'been', 'has',
        'have', 'had', 'not', 'this', 'that', 'from', 'you', 'we', 'they', 'he',
        'she', 'its', 'our', 'your', 'about', 'which', 'their', 'will', 'can',
        'more', 'all', 'also', 'into', 'than', 'then', 'some', 'what', 'when',
      ])
      const text = input.toLowerCase()
      const words = text.match(/\b[a-z]{4,}\b/g) || []

      // Single keywords
      const singleFreq: Record<string, number> = {}
      words.filter((w: string) => !stopWords.has(w)).forEach((w: string) => {
        singleFreq[w] = (singleFreq[w] || 0) + 1
      })

      // Bigrams
      const bigrams: Record<string, number> = {}
      for (let i = 0; i < words.length - 1; i++) {
        if (!stopWords.has(words[i]) && !stopWords.has(words[i + 1])) {
          const bigram = `${words[i]} ${words[i + 1]}`
          bigrams[bigram] = (bigrams[bigram] || 0) + 1
        }
      }

      const topSingle = Object.entries(singleFreq).sort((a, b) => b[1] - a[1]).slice(0, 20)
      const topBigrams = Object.entries(bigrams).sort((a, b) => b[1] - a[1]).slice(0, 10)

      return Response.json({
        keywords: topSingle.map(([word, count]) => ({ word, count, density: ((count / words.length) * 100).toFixed(2) })),
        phrases: topBigrams.map(([phrase, count]) => ({ phrase, count })),
        totalWords: words.length,
        uniqueWords: Object.keys(singleFreq).length,
      })
    }

    // ── Robots.txt generator ────────────────────────────────
    if (action === 'robots') {
      const { sitemapUrl = 'https://example.com/sitemap.xml', disallowed = ['/admin/', '/private/'], crawlDelay } = options

      const lines: string[] = [
        '# Robots.txt generated by Multiverse Tools',
        '',
        'User-agent: *',
        'Allow: /',
        ...disallowed.map((d: string) => `Disallow: ${d}`),
        crawlDelay ? `Crawl-delay: ${crawlDelay}` : '',
        '',
        '# Google',
        'User-agent: Googlebot',
        'Allow: /',
        '',
        '# Bing',
        'User-agent: Bingbot',
        'Allow: /',
        '',
        '# Prevent AI scrapers',
        'User-agent: GPTBot',
        'Disallow: /',
        'User-agent: ChatGPT-User',
        'Disallow: /',
        'User-agent: Google-Extended',
        'Disallow: /',
        '',
        `Sitemap: ${sitemapUrl}`,
      ].filter(l => l !== null)

      return Response.json({ robotsTxt: lines.join('\n') })
    }

    // ── Sitemap generator ───────────────────────────────────
    if (action === 'sitemap') {
      const { baseUrl = 'https://example.com', paths = ['/', '/about', '/contact'] } = options
      const urls = Array.isArray(paths) ? paths : paths.split('\n').filter(Boolean)
      const date = new Date().toISOString().split('T')[0]

      const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
        http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
${urls.map((p: string) => `  <url>
    <loc>${baseUrl}${p.startsWith('/') ? p : '/' + p}</loc>
    <lastmod>${date}</lastmod>
    <changefreq>${p === '/' ? 'daily' : 'weekly'}</changefreq>
    <priority>${p === '/' ? '1.0' : '0.8'}</priority>
  </url>`).join('\n')}
</urlset>`

      return Response.json({ sitemap: xml, urlCount: urls.length })
    }

    // ── Structured data (Schema.org) ────────────────────────
    if (action === 'schema') {
      const type = options.type || 'Article'
      const schemas: Record<string, object> = {
        Article: {
          '@context': 'https://schema.org',
          '@type': 'Article',
          headline: options.title || 'Article Title',
          description: options.description || 'Article description',
          author: { '@type': 'Person', name: options.author || 'Author Name' },
          datePublished: options.date || new Date().toISOString().split('T')[0],
          publisher: { '@type': 'Organization', name: options.publisher || 'Publisher Name' },
        },
        Product: {
          '@context': 'https://schema.org',
          '@type': 'Product',
          name: options.name || 'Product Name',
          description: options.description || 'Product description',
          brand: { '@type': 'Brand', name: options.brand || 'Brand Name' },
          offers: { '@type': 'Offer', price: options.price || '0', priceCurrency: options.currency || 'USD' },
        },
        FAQ: {
          '@context': 'https://schema.org',
          '@type': 'FAQPage',
          mainEntity: [
            { '@type': 'Question', name: 'Question 1?', acceptedAnswer: { '@type': 'Answer', text: 'Answer 1.' } },
            { '@type': 'Question', name: 'Question 2?', acceptedAnswer: { '@type': 'Answer', text: 'Answer 2.' } },
          ],
        },
      }

      const schema = schemas[type] || schemas.Article
      return Response.json({
        schema: JSON.stringify(schema, null, 2),
        scriptTag: `<script type="application/ld+json">\n${JSON.stringify(schema, null, 2)}\n</script>`,
      })
    }

    if (action === 'social-preview') {
      const target = await assertSafeRemoteUrl(input || options.url || '')
      const response = await fetch(target, {
        headers: {
          'User-Agent': 'Mozilla/5.0 (compatible; MultiverseToolsBot/1.0; +https://multiverse-tools.vercel.app)',
          Accept: 'text/html,application/xhtml+xml',
        },
        redirect: 'follow',
        signal: AbortSignal.timeout(10000),
      })

      const html = await response.text()
      const title =
        getMetaContent(html, /<meta[^>]+property=["']og:title["'][^>]+content=["']([^"]*)["']/i) ||
        getMetaContent(html, /<meta[^>]+name=["']twitter:title["'][^>]+content=["']([^"]*)["']/i) ||
        getMetaContent(html, /<title>([^<]*)<\/title>/i)
      const description =
        getMetaContent(html, /<meta[^>]+property=["']og:description["'][^>]+content=["']([^"]*)["']/i) ||
        getMetaContent(html, /<meta[^>]+name=["']twitter:description["'][^>]+content=["']([^"]*)["']/i) ||
        getMetaContent(html, /<meta[^>]+name=["']description["'][^>]+content=["']([^"]*)["']/i)
      const ogImage = absolutizeUrl(
        getMetaContent(html, /<meta[^>]+property=["']og:image["'][^>]+content=["']([^"]*)["']/i) ||
          getMetaContent(html, /<meta[^>]+name=["']twitter:image["'][^>]+content=["']([^"]*)["']/i),
        target
      )

      return Response.json({
        url: response.url,
        status: response.status,
        title,
        description,
        canonical: absolutizeUrl(
          getMetaContent(html, /<link[^>]+rel=["']canonical["'][^>]+href=["']([^"]*)["']/i),
          target
        ),
        siteName: getMetaContent(html, /<meta[^>]+property=["']og:site_name["'][^>]+content=["']([^"]*)["']/i),
        ogType: getMetaContent(html, /<meta[^>]+property=["']og:type["'][^>]+content=["']([^"]*)["']/i) || 'website',
        robots: getMetaContent(html, /<meta[^>]+name=["']robots["'][^>]+content=["']([^"]*)["']/i) || 'index, follow',
        twitterCard:
          getMetaContent(html, /<meta[^>]+name=["']twitter:card["'][^>]+content=["']([^"]*)["']/i) ||
          'summary_large_image',
        ogImage,
        titleLength: title.length,
        descriptionLength: description.length,
      })
    }

    return err(`Unknown SEO action: ${action}`)
  } catch (e) {
    return err(`SEO tool failed: ${(e as Error).message}`, 500)
  }
}
