export const DISCOVER_SEARCH_INTENT_FORMATS = [
  'How to ...',
  'What is ...',
  'Best ...',
  'Top 10 ...',
  'How to make money ...',
  'How to start ...',
  'Free ...',
  '... near me',
  '... vs ...',
  'Tips for ...',
] as const

export const DISCOVER_HIGH_TRAFFIC_SEARCH_BUCKETS = [
  {
    category: 'Money & Online Income',
    priority: 'highest',
    ideas: [
      'How to make money online',
      'How to earn money from home',
      'Best online jobs for students',
      'How to start freelancing',
      'How to earn money using mobile',
      'Passive income ideas',
      'How to earn money on YouTube',
      'Blogging for beginners',
      'How affiliate marketing works',
      'How to start dropshipping',
      'Free online income ideas',
      'Best freelancing websites for beginners',
      'How to get remote jobs',
      'How to start a side hustle',
      'How to make money with AI',
    ],
  },
  {
    category: 'Tech / Mobile',
    priority: 'highest',
    ideas: [
      'Best apps for earning money',
      'Best mobile under 20000',
      'Android tips and tricks',
      'How to increase phone speed',
      'WhatsApp tricks',
      'Instagram growth tips',
      'Best AI apps for mobile users',
      'How to use ChatGPT',
      'Best AI tools for daily work',
      'How to fix phone battery drain',
      'How to fix phone overheating',
      'Best phones for battery life',
      'Best student apps for Android',
      'Free editing apps',
      'Best note taking apps',
    ],
  },
  {
    category: 'Education / Students',
    priority: 'highest',
    ideas: [
      'How to study effectively',
      'Time management for students',
      'Best courses after 12th',
      'How to concentrate on studies',
      'Study tips for exams',
      'How to score high marks',
      'How to prepare for government exams',
      'UPSC preparation tips',
      'Free online courses',
      'Skill development ideas',
      'How to build a study plan',
      'Best apps for students',
      'Best skills to learn as a student',
      'How to avoid distractions while studying',
      'How to take better notes',
    ],
  },
  {
    category: 'Business / Startup',
    priority: 'high',
    ideas: [
      'How to start a business',
      'Small business ideas',
      'Low investment business ideas',
      'Online business ideas',
      'Startup ideas 2026',
      'How franchise business works',
      'Dropshipping India guide',
      'How digital marketing works',
      'Side business ideas',
      'Work from home business ideas',
      'Best tools for startups',
      'How to validate a startup idea',
      'Best business ideas for students',
      'How to start an online store',
      'How to choose a business niche',
    ],
  },
  {
    category: 'Self Improvement',
    priority: 'high',
    ideas: [
      'How to be confident',
      'How to improve communication skills',
      'Morning routine ideas',
      'Productivity tips',
      'How to stop procrastination',
      'Success habits',
      'How to change your mindset',
      'Goal setting tips',
      'How to stay motivated',
      'How to build discipline',
      'How to build self respect',
      'How to improve focus',
      'Best books for self improvement',
      'How to become consistent',
      'How to manage your time better',
    ],
  },
  {
    category: 'Lifestyle / Health',
    priority: 'high',
    ideas: [
      'How to lose weight at home',
      'Home workout plan',
      'Healthy diet plan',
      'Skin care routine',
      'Hair growth tips',
      'Mental health tips',
      'Yoga benefits',
      'Sleep improvement tips',
      'How to meditate',
      'Fitness tips for beginners',
      'Best morning habits for health',
      'How to improve sleep quality',
      'Simple home exercises',
      'How to stay fit without gym',
      'Healthy routine for busy people',
    ],
  },
  {
    category: 'Trending / Viral',
    priority: 'highest',
    ideas: [
      'Most useful AI tools right now',
      'Make money with AI',
      'YouTube automation',
      'Instagram reels ideas',
      'How to create a viral video',
      'Content creation tips',
      'How personal branding works',
      'Online earning without investment',
      'Freelancing websites list',
      'How to find remote jobs',
      'Best AI tools for creators',
      'Best apps for reels editing',
      'How to grow on Instagram',
      'Best niches for YouTube automation',
      'How to start content creation',
    ],
  },
  {
    category: 'AI / Models / Tools',
    priority: 'highest',
    ideas: [
      'Best AI models for coding',
      'Best AI tools for students',
      'Best AI tools for business',
      'Best AI tools for image generation',
      'Best AI tools for video generation',
      'What is an LLM',
      'AI model comparison',
      'ChatGPT vs Claude',
      'Claude vs Gemini',
      'Best free AI tools',
      'How to choose an AI model',
      'How to use AI for work',
      'How to use AI for studying',
      'Best AI tools for YouTube',
      'Best AI tools for writing',
    ],
  },
] as const
