export type ToolTag = 'new' | 'trending' | 'beta' | 'hot' | 'free'

export interface Tool {
  id: string
  name: string
  description: string
  category: string
  categorySlug: string
  icon: string
  slug: string
  tags: ToolTag[]
  popular?: boolean
  implemented: boolean
  inputType?: 'file' | 'text' | 'url' | 'both' | 'none'
  outputType?: 'file' | 'text' | 'preview' | 'both'
  acceptedFormats?: string[]
}

export interface Category {
  id: string
  name: string
  slug: string
  description: string
  icon: string
  color: string
  gradient: string
  toolCount?: number
}

export const CATEGORIES: Category[] = [
  {
    id: 'pdf',
    name: 'PDF Tools',
    slug: 'pdf',
    description: 'Convert, compress, merge and edit PDF files',
    icon: 'FileText',
    color: 'red',
    gradient: 'from-red-500 to-orange-500',
  },
  {
    id: 'image',
    name: 'Image Tools',
    slug: 'image',
    description: 'Resize, compress, convert and edit images',
    icon: 'Image',
    color: 'blue',
    gradient: 'from-blue-500 to-cyan-500',
  },
  {
    id: 'video',
    name: 'Video Tools',
    slug: 'video',
    description: 'Convert, compress and edit videos',
    icon: 'Video',
    color: 'purple',
    gradient: 'from-purple-500 to-pink-500',
  },
  {
    id: 'audio',
    name: 'Audio Tools',
    slug: 'audio',
    description: 'Convert, edit and process audio files',
    icon: 'Music',
    color: 'green',
    gradient: 'from-green-500 to-teal-500',
  },
  {
    id: 'text',
    name: 'Text Tools',
    slug: 'text',
    description: 'Format, convert and analyze text content',
    icon: 'Type',
    color: 'yellow',
    gradient: 'from-yellow-500 to-amber-500',
  },
  {
    id: 'dev',
    name: 'Dev Tools',
    slug: 'dev',
    description: 'JSON, Base64, regex and developer utilities',
    icon: 'Code',
    color: 'slate',
    gradient: 'from-slate-600 to-slate-800',
  },
  {
    id: 'seo',
    name: 'SEO Tools',
    slug: 'seo',
    description: 'Meta tags, keywords and SEO analysis',
    icon: 'Search',
    color: 'indigo',
    gradient: 'from-indigo-500 to-blue-600',
  },
  {
    id: 'calculator',
    name: 'Calculators',
    slug: 'calculator',
    description: 'EMI, currency, BMI and more calculators',
    icon: 'Calculator',
    color: 'teal',
    gradient: 'from-teal-500 to-emerald-500',
  },
  {
    id: 'file',
    name: 'File Tools',
    slug: 'file',
    description: 'Compress, extract and manage files',
    icon: 'Folder',
    color: 'orange',
    gradient: 'from-orange-500 to-yellow-500',
  },
  {
    id: 'ai',
    name: 'AI Tools',
    slug: 'ai',
    description: 'AI writing, summarize and generate content',
    icon: 'Bot',
    color: 'violet',
    gradient: 'from-violet-500 to-purple-600',
  },
]

const ALL_TOOLS: Tool[] = [
  // ── PDF TOOLS ──────────────────────────────────────────────────────────────
  {
    id: 'pdf-merge',
    name: 'Merge PDF',
    description: 'Combine multiple PDF files into one',
    category: 'PDF Tools',
    categorySlug: 'pdf',
    icon: 'Combine',
    slug: 'merge-pdf',
    tags: ['trending'],
    popular: true,
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.pdf'],
  },
  {
    id: 'pdf-split',
    name: 'Split PDF',
    description: 'Split PDF into separate pages or ranges',
    category: 'PDF Tools',
    categorySlug: 'pdf',
    icon: 'Scissors',
    slug: 'split-pdf',
    tags: ['trending'],
    popular: true,
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.pdf'],
  },
  {
    id: 'pdf-compress',
    name: 'Compress PDF',
    description: 'Reduce PDF file size without quality loss',
    category: 'PDF Tools',
    categorySlug: 'pdf',
    icon: 'Minimize2',
    slug: 'compress-pdf',
    tags: ['hot'],
    popular: true,
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.pdf'],
  },
  {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    description: 'Convert PDF documents to editable Word files',
    category: 'PDF Tools',
    categorySlug: 'pdf',
    icon: 'FileType',
    slug: 'pdf-to-word',
    tags: ['trending'],
    popular: true,
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.pdf'],
  },
  {
    id: 'pdf-to-excel',
    name: 'PDF to Excel',
    description: 'Extract table data from PDF files into Excel workbooks',
    category: 'PDF Tools',
    categorySlug: 'pdf',
    icon: 'Table2',
    slug: 'pdf-to-excel',
    tags: ['trending', 'new'],
    popular: true,
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.pdf'],
  },
  {
    id: 'pdf-to-jpg',
    name: 'PDF to JPG',
    description: 'Convert PDF pages to JPG images',
    category: 'PDF Tools',
    categorySlug: 'pdf',
    icon: 'Image',
    slug: 'pdf-to-jpg',
    tags: ['new'],
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.pdf'],
  },
  {
    id: 'pdf-ocr',
    name: 'PDF OCR',
    description: 'Extract readable text from scanned PDF files',
    category: 'PDF Tools',
    categorySlug: 'pdf',
    icon: 'ScanText',
    slug: 'pdf-ocr',
    tags: ['hot', 'trending'],
    popular: true,
    implemented: true,
    inputType: 'file',
    outputType: 'text',
    acceptedFormats: ['.pdf'],
  },
  {
    id: 'jpg-to-pdf',
    name: 'JPG to PDF',
    description: 'Convert JPG images to PDF format',
    category: 'PDF Tools',
    categorySlug: 'pdf',
    icon: 'FilePlus',
    slug: 'jpg-to-pdf',
    tags: ['new'],
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp'],
  },
  {
    id: 'pdf-rotate',
    name: 'Rotate PDF',
    description: 'Rotate PDF pages to correct orientation',
    category: 'PDF Tools',
    categorySlug: 'pdf',
    icon: 'RotateCcw',
    slug: 'rotate-pdf',
    tags: [],
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.pdf'],
  },
  {
    id: 'pdf-protect',
    name: 'Protect PDF',
    description: 'Add password protection to PDF files',
    category: 'PDF Tools',
    categorySlug: 'pdf',
    icon: 'Lock',
    slug: 'protect-pdf',
    tags: ['new'],
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.pdf'],
  },
  {
    id: 'pdf-unlock',
    name: 'Unlock PDF',
    description: 'Remove password from PDF files',
    category: 'PDF Tools',
    categorySlug: 'pdf',
    icon: 'Unlock',
    slug: 'unlock-pdf',
    tags: [],
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.pdf'],
  },
  {
    id: 'pdf-watermark',
    name: 'Add Watermark',
    description: 'Add custom text or image watermark to PDF',
    category: 'PDF Tools',
    categorySlug: 'pdf',
    icon: 'Stamp',
    slug: 'pdf-watermark',
    tags: ['beta'],
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.pdf'],
  },
  {
    id: 'word-to-pdf',
    name: 'Word to PDF',
    description: 'Convert Word DOCX files to PDF',
    category: 'PDF Tools',
    categorySlug: 'pdf',
    icon: 'FileOutput',
    slug: 'word-to-pdf',
    tags: ['trending'],
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.docx', '.doc'],
  },
  {
    id: 'pdf-translator',
    name: 'PDF Translator',
    description: 'Translate PDF content into another language',
    category: 'PDF Tools',
    categorySlug: 'pdf',
    icon: 'Languages',
    slug: 'pdf-translator',
    tags: ['new', 'trending'],
    popular: true,
    implemented: true,
    inputType: 'file',
    outputType: 'text',
    acceptedFormats: ['.pdf'],
  },
  {
    id: 'pdf-summarizer',
    name: 'PDF Summarizer',
    description: 'Generate short or detailed summaries from PDF files',
    category: 'PDF Tools',
    categorySlug: 'pdf',
    icon: 'Sparkles',
    slug: 'pdf-summarizer',
    tags: ['hot', 'trending'],
    popular: true,
    implemented: true,
    inputType: 'file',
    outputType: 'text',
    acceptedFormats: ['.pdf'],
  },
  {
    id: 'pdf-to-text',
    name: 'PDF to Text',
    description: 'Extract text content from PDF files',
    category: 'PDF Tools',
    categorySlug: 'pdf',
    icon: 'FileSearch',
    slug: 'pdf-to-text',
    tags: [],
    implemented: true,
    inputType: 'file',
    outputType: 'text',
    acceptedFormats: ['.pdf'],
  },
  {
    id: 'pdf-metadata',
    name: 'PDF Metadata',
    description: 'View and edit PDF metadata properties',
    category: 'PDF Tools',
    categorySlug: 'pdf',
    icon: 'BadgeInfo',
    slug: 'pdf-metadata',
    tags: ['beta'],
    implemented: true,
    inputType: 'file',
    outputType: 'both',
    acceptedFormats: ['.pdf'],
  },

  // ── IMAGE TOOLS ────────────────────────────────────────────────────────────
  {
    id: 'image-compress',
    name: 'Compress Image',
    description: 'Reduce image size while preserving quality',
    category: 'Image Tools',
    categorySlug: 'image',
    icon: 'ImageDown',
    slug: 'compress-image',
    tags: ['hot'],
    popular: true,
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp'],
  },
  {
    id: 'image-resize',
    name: 'Resize Image',
    description: 'Resize images to any custom dimensions',
    category: 'Image Tools',
    categorySlug: 'image',
    icon: 'Maximize2',
    slug: 'resize-image',
    tags: ['trending'],
    popular: true,
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp', '.gif'],
  },
  {
    id: 'image-convert',
    name: 'Convert Image',
    description: 'Convert images between JPG, PNG, WebP formats',
    category: 'Image Tools',
    categorySlug: 'image',
    icon: 'RefreshCw',
    slug: 'convert-image',
    tags: ['new'],
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp', '.gif', '.bmp'],
  },
  {
    id: 'image-crop',
    name: 'Crop Image',
    description: 'Crop images to custom sizes or aspect ratios',
    category: 'Image Tools',
    categorySlug: 'image',
    icon: 'Crop',
    slug: 'crop-image',
    tags: [],
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp'],
  },
  {
    id: 'bg-remover',
    name: 'Remove Background',
    description: 'Remove image backgrounds instantly with local AI processing',
    category: 'Image Tools',
    categorySlug: 'image',
    icon: 'Eraser',
    slug: 'remove-background',
    tags: ['hot', 'trending'],
    popular: true,
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp'],
  },
  {
    id: 'passport-photo-maker',
    name: 'Passport Photo Maker',
    description: 'Create a clean passport-style photo with a white background',
    category: 'Image Tools',
    categorySlug: 'image',
    icon: 'FileUser',
    slug: 'passport-photo-maker',
    tags: ['new', 'hot'],
    popular: true,
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp'],
  },
  {
    id: 'blur-background',
    name: 'Blur Background',
    description: 'Keep the subject sharp and blur the background for portraits',
    category: 'Image Tools',
    categorySlug: 'image',
    icon: 'Aperture',
    slug: 'blur-background',
    tags: ['new', 'trending'],
    popular: true,
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp'],
  },
  {
    id: 'image-to-text',
    name: 'Image to Text (OCR)',
    description: 'Extract text from images using OCR',
    category: 'Image Tools',
    categorySlug: 'image',
    icon: 'ScanText',
    slug: 'image-to-text',
    tags: ['trending'],
    implemented: true,
    inputType: 'file',
    outputType: 'text',
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp'],
  },
  {
    id: 'qr-generate',
    name: 'QR Code Generator',
    description: 'Generate QR codes for URLs, text and more',
    category: 'Image Tools',
    categorySlug: 'image',
    icon: 'QrCode',
    slug: 'qr-code-generator',
    tags: ['trending'],
    popular: true,
    implemented: true,
    inputType: 'text',
    outputType: 'file',
  },
  {
    id: 'color-picker',
    name: 'Color Picker',
    description: 'Pick colors from any image file',
    category: 'Image Tools',
    categorySlug: 'image',
    icon: 'Pipette',
    slug: 'color-picker',
    tags: ['new'],
    implemented: true,
    inputType: 'file',
    outputType: 'text',
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp'],
  },
  {
    id: 'palette-gen',
    name: 'Color Palette Generator',
    description: 'Generate beautiful color palettes from images',
    category: 'Image Tools',
    categorySlug: 'image',
    icon: 'Palette',
    slug: 'color-palette-generator',
    tags: ['new'],
    implemented: true,
    inputType: 'both',
    outputType: 'text',
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp'],
  },
  {
    id: 'img-to-base64',
    name: 'Image to Base64',
    description: 'Convert images to Base64 encoded strings',
    category: 'Image Tools',
    categorySlug: 'image',
    icon: 'Binary',
    slug: 'image-to-base64',
    tags: [],
    implemented: true,
    inputType: 'file',
    outputType: 'text',
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp', '.gif', '.svg'],
  },
  {
    id: 'favicon-gen',
    name: 'Favicon Generator',
    description: 'Generate favicon ICO from any image',
    category: 'Image Tools',
    categorySlug: 'image',
    icon: 'Star',
    slug: 'favicon-generator',
    tags: ['new'],
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.svg'],
  },
  {
    id: 'image-flip',
    name: 'Flip & Rotate',
    description: 'Flip or rotate images instantly',
    category: 'Image Tools',
    categorySlug: 'image',
    icon: 'FlipHorizontal',
    slug: 'flip-rotate-image',
    tags: [],
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp'],
  },
  {
    id: 'watermark-image',
    name: 'Add Watermark',
    description: 'Add text or image watermark to photos',
    category: 'Image Tools',
    categorySlug: 'image',
    icon: 'Stamp',
    slug: 'add-watermark-image',
    tags: ['beta'],
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp'],
  },
  {
    id: 'svg-to-png',
    name: 'SVG to PNG',
    description: 'Convert SVG vector graphics to PNG',
    category: 'Image Tools',
    categorySlug: 'image',
    icon: 'PenTool',
    slug: 'svg-to-png',
    tags: [],
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.svg'],
  },

  // ── VIDEO TOOLS ────────────────────────────────────────────────────────────
  {
    id: 'all-in-one-video-downloader',
    name: 'All-in-One Video Downloader',
    description: 'Download MP4, WEBM, MP3, M4A and HD thumbnails from supported video links',
    category: 'Video Tools',
    categorySlug: 'video',
    icon: 'Download',
    slug: 'all-in-one-video-downloader',
    tags: ['trending', 'hot'],
    popular: true,
    implemented: true,
    inputType: 'url',
    outputType: 'file',
  },
  {
    id: 'video-compress',
    name: 'Compress Video',
    description: 'Reduce video file size without quality loss',
    category: 'Video Tools',
    categorySlug: 'video',
    icon: 'Film',
    slug: 'compress-video',
    tags: ['trending'],
    popular: true,
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.mp4', '.avi', '.mov', '.mkv', '.webm'],
  },
  {
    id: 'video-to-mp3',
    name: 'Video to MP3',
    description: 'Extract audio MP3 from video files',
    category: 'Video Tools',
    categorySlug: 'video',
    icon: 'Music',
    slug: 'video-to-mp3',
    tags: ['hot'],
    popular: true,
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.mp4', '.avi', '.mov', '.mkv', '.webm'],
  },
  {
    id: 'video-trim',
    name: 'Trim Video',
    description: 'Cut and trim video clips easily',
    category: 'Video Tools',
    categorySlug: 'video',
    icon: 'Scissors',
    slug: 'trim-video',
    tags: [],
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.mp4', '.avi', '.mov', '.webm'],
  },
  {
    id: 'video-to-gif',
    name: 'Video to GIF',
    description: 'Convert video clips to animated GIFs',
    category: 'Video Tools',
    categorySlug: 'video',
    icon: 'Clapperboard',
    slug: 'video-to-gif',
    tags: ['trending', 'new'],
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.mp4', '.avi', '.mov', '.webm'],
  },
  {
    id: 'yt-thumbnail',
    name: 'YT Thumbnail Downloader',
    description: 'Download YouTube video thumbnails',
    category: 'Video Tools',
    categorySlug: 'video',
    icon: 'Download',
    slug: 'youtube-thumbnail-downloader',
    tags: ['hot'],
    popular: true,
    implemented: true,
    inputType: 'url',
    outputType: 'file',
  },
  {
    id: 'video-speed',
    name: 'Change Video Speed',
    description: 'Speed up or slow down video playback',
    category: 'Video Tools',
    categorySlug: 'video',
    icon: 'Gauge',
    slug: 'change-video-speed',
    tags: ['beta'],
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.mp4', '.webm', '.mov'],
  },
  {
    id: 'video-mute',
    name: 'Mute Video',
    description: 'Remove audio track from video files',
    category: 'Video Tools',
    categorySlug: 'video',
    icon: 'VolumeX',
    slug: 'mute-video',
    tags: [],
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.mp4', '.avi', '.mov', '.webm'],
  },
  {
    id: 'gif-maker',
    name: 'GIF Maker',
    description: 'Create animated GIFs from images',
    category: 'Video Tools',
    categorySlug: 'video',
    icon: 'Play',
    slug: 'gif-maker',
    tags: ['new'],
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp'],
  },

  // ── AUDIO TOOLS ────────────────────────────────────────────────────────────
  {
    id: 'audio-convert',
    name: 'Convert Audio',
    description: 'Convert between MP3, WAV, AAC, FLAC formats',
    category: 'Audio Tools',
    categorySlug: 'audio',
    icon: 'AudioWaveform',
    slug: 'convert-audio',
    tags: [],
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.mp3', '.wav', '.aac', '.flac', '.ogg'],
  },
  {
    id: 'audio-trim',
    name: 'Trim Audio',
    description: 'Cut and trim audio clips to exact length',
    category: 'Audio Tools',
    categorySlug: 'audio',
    icon: 'Scissors',
    slug: 'trim-audio',
    tags: [],
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.mp3', '.wav', '.ogg', '.aac'],
  },
  {
    id: 'tts',
    name: 'Text to Speech',
    description: 'Convert text to natural voice audio',
    category: 'Audio Tools',
    categorySlug: 'audio',
    icon: 'Mic',
    slug: 'text-to-speech',
    tags: ['trending', 'hot'],
    popular: true,
    implemented: true,
    inputType: 'text',
    outputType: 'file',
  },
  {
    id: 'stt',
    name: 'Speech to Text',
    description: 'Transcribe audio to text using AI',
    category: 'Audio Tools',
    categorySlug: 'audio',
    icon: 'MicOff',
    slug: 'speech-to-text',
    tags: ['trending'],
    implemented: true,
    inputType: 'file',
    outputType: 'text',
    acceptedFormats: ['.mp3', '.wav', '.ogg', '.m4a'],
  },
  {
    id: 'audio-merge',
    name: 'Merge Audio',
    description: 'Combine multiple audio files into one',
    category: 'Audio Tools',
    categorySlug: 'audio',
    icon: 'Combine',
    slug: 'merge-audio',
    tags: [],
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.mp3', '.wav', '.ogg'],
  },
  {
    id: 'audio-compress',
    name: 'Compress Audio',
    description: 'Reduce audio file size with quality options',
    category: 'Audio Tools',
    categorySlug: 'audio',
    icon: 'Minimize2',
    slug: 'compress-audio',
    tags: [],
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.mp3', '.wav', '.flac'],
  },
  {
    id: 'audio-recorder',
    name: 'Audio Recorder',
    description: 'Record audio directly in your browser',
    category: 'Audio Tools',
    categorySlug: 'audio',
    icon: 'Mic2',
    slug: 'audio-recorder',
    tags: ['new'],
    implemented: true,
    inputType: 'none',
    outputType: 'file',
  },
  {
    id: 'bpm-detector',
    name: 'BPM Detector',
    description: 'Detect beats per minute of audio tracks',
    category: 'Audio Tools',
    categorySlug: 'audio',
    icon: 'Activity',
    slug: 'bpm-detector',
    tags: ['beta'],
    implemented: true,
    inputType: 'file',
    outputType: 'text',
    acceptedFormats: ['.mp3', '.wav', '.ogg'],
  },

  // ── TEXT TOOLS ─────────────────────────────────────────────────────────────
  {
    id: 'word-counter',
    name: 'Word Counter',
    description: 'Count words, characters, sentences and paragraphs',
    category: 'Text Tools',
    categorySlug: 'text',
    icon: 'AlignLeft',
    slug: 'word-counter',
    tags: ['trending'],
    popular: true,
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'case-converter',
    name: 'Text Case Converter',
    description: 'Convert text to any case format',
    category: 'Text Tools',
    categorySlug: 'text',
    icon: 'CaseUpper',
    slug: 'text-case-converter',
    tags: [],
    popular: true,
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'lorem-ipsum',
    name: 'Lorem Ipsum Generator',
    description: 'Generate placeholder lorem ipsum text',
    category: 'Text Tools',
    categorySlug: 'text',
    icon: 'FileText',
    slug: 'lorem-ipsum-generator',
    tags: [],
    implemented: true,
    inputType: 'none',
    outputType: 'text',
  },
  {
    id: 'text-diff',
    name: 'Text Diff Checker',
    description: 'Compare two texts and find differences',
    category: 'Text Tools',
    categorySlug: 'text',
    icon: 'GitCompare',
    slug: 'text-diff-checker',
    tags: ['new'],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'duplicate-remover',
    name: 'Remove Duplicate Lines',
    description: 'Remove duplicate lines from text',
    category: 'Text Tools',
    categorySlug: 'text',
    icon: 'Filter',
    slug: 'remove-duplicate-lines',
    tags: [],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'text-reverser',
    name: 'Text Reverser',
    description: 'Reverse words or characters in text',
    category: 'Text Tools',
    categorySlug: 'text',
    icon: 'FlipHorizontal',
    slug: 'text-reverser',
    tags: [],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'md-to-html',
    name: 'Markdown to HTML',
    description: 'Convert Markdown text to HTML markup',
    category: 'Text Tools',
    categorySlug: 'text',
    icon: 'Code',
    slug: 'markdown-to-html',
    tags: ['new'],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'csv-to-json',
    name: 'CSV to JSON',
    description: 'Convert CSV data to JSON format',
    category: 'Text Tools',
    categorySlug: 'text',
    icon: 'Table',
    slug: 'csv-to-json',
    tags: [],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'json-to-csv',
    name: 'JSON to CSV',
    description: 'Convert JSON arrays to CSV spreadsheet',
    category: 'Text Tools',
    categorySlug: 'text',
    icon: 'Table2',
    slug: 'json-to-csv',
    tags: [],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'string-extractor',
    name: 'String Extractor',
    description: 'Extract URLs, emails, and patterns from text',
    category: 'Text Tools',
    categorySlug: 'text',
    icon: 'Magnet',
    slug: 'string-extractor',
    tags: ['beta'],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'readability',
    name: 'Readability Score',
    description: 'Analyze text readability and grade level',
    category: 'Text Tools',
    categorySlug: 'text',
    icon: 'BookOpen',
    slug: 'readability-score',
    tags: ['new'],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'keyword-density',
    name: 'Keyword Density',
    description: 'Analyze keyword frequency in your content',
    category: 'Text Tools',
    categorySlug: 'text',
    icon: 'BarChart',
    slug: 'keyword-density',
    tags: [],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },

  // ── DEV TOOLS ──────────────────────────────────────────────────────────────
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Format, validate and beautify JSON data',
    category: 'Dev Tools',
    categorySlug: 'dev',
    icon: 'Braces',
    slug: 'json-formatter',
    tags: ['hot'],
    popular: true,
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'base64',
    name: 'Base64 Encoder/Decoder',
    description: 'Encode and decode Base64 strings instantly',
    category: 'Dev Tools',
    categorySlug: 'dev',
    icon: 'Binary',
    slug: 'base64-encoder-decoder',
    tags: [],
    popular: true,
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'url-encoder',
    name: 'URL Encoder/Decoder',
    description: 'Encode and decode URL components',
    category: 'Dev Tools',
    categorySlug: 'dev',
    icon: 'Link',
    slug: 'url-encoder-decoder',
    tags: [],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode and inspect JWT token payloads',
    category: 'Dev Tools',
    categorySlug: 'dev',
    icon: 'KeyRound',
    slug: 'jwt-decoder',
    tags: ['trending'],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'uuid-gen',
    name: 'UUID Generator',
    description: 'Generate unique UUIDs and GUIDs',
    category: 'Dev Tools',
    categorySlug: 'dev',
    icon: 'Hash',
    slug: 'uuid-generator',
    tags: [],
    implemented: true,
    inputType: 'none',
    outputType: 'text',
  },
  {
    id: 'hash-gen',
    name: 'Hash Generator',
    description: 'Generate MD5, SHA-1, SHA-256 hashes',
    category: 'Dev Tools',
    categorySlug: 'dev',
    icon: 'Shield',
    slug: 'hash-generator',
    tags: [],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test and debug regular expressions live',
    category: 'Dev Tools',
    categorySlug: 'dev',
    icon: 'Regex',
    slug: 'regex-tester',
    tags: ['trending'],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'css-minifier',
    name: 'CSS Minifier',
    description: 'Minify CSS code to reduce file size',
    category: 'Dev Tools',
    categorySlug: 'dev',
    icon: 'Minimize',
    slug: 'css-minifier',
    tags: [],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'js-minifier',
    name: 'JS Minifier',
    description: 'Minify JavaScript code for production',
    category: 'Dev Tools',
    categorySlug: 'dev',
    icon: 'Zap',
    slug: 'js-minifier',
    tags: [],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'color-converter',
    name: 'Color Converter',
    description: 'Convert HEX, RGB, HSL color formats',
    category: 'Dev Tools',
    categorySlug: 'dev',
    icon: 'Palette',
    slug: 'color-converter',
    tags: ['new'],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'gradient-gen',
    name: 'Gradient Generator',
    description: 'Create and export CSS gradients visually',
    category: 'Dev Tools',
    categorySlug: 'dev',
    icon: 'Paintbrush',
    slug: 'gradient-generator',
    tags: ['new'],
    implemented: true,
    inputType: 'none',
    outputType: 'text',
  },
  {
    id: 'cron-gen',
    name: 'Cron Expression Generator',
    description: 'Build and explain cron job expressions',
    category: 'Dev Tools',
    categorySlug: 'dev',
    icon: 'Clock',
    slug: 'cron-generator',
    tags: ['beta'],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'gitignore-gen',
    name: '.gitignore Generator',
    description: 'Generate .gitignore for any tech stack',
    category: 'Dev Tools',
    categorySlug: 'dev',
    icon: 'GitBranch',
    slug: 'gitignore-generator',
    tags: ['new'],
    implemented: true,
    inputType: 'none',
    outputType: 'text',
  },
  {
    id: 'api-tester',
    name: 'API Tester',
    description: 'Test REST APIs with custom headers and body',
    category: 'Dev Tools',
    categorySlug: 'dev',
    icon: 'Globe',
    slug: 'api-tester',
    tags: ['beta'],
    implemented: true,
    inputType: 'url',
    outputType: 'text',
  },

  // ── SEO TOOLS ──────────────────────────────────────────────────────────────
  {
    id: 'meta-tag-gen',
    name: 'Meta Tag Generator',
    description: 'Generate SEO meta tags for any webpage',
    category: 'SEO Tools',
    categorySlug: 'seo',
    icon: 'Tags',
    slug: 'meta-tag-generator',
    tags: ['trending'],
    popular: true,
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'og-gen',
    name: 'Open Graph Generator',
    description: 'Generate Open Graph social preview tags',
    category: 'SEO Tools',
    categorySlug: 'seo',
    icon: 'Share2',
    slug: 'open-graph-generator',
    tags: ['new'],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'robots-txt-gen',
    name: 'Robots.txt Generator',
    description: 'Generate robots.txt for search engines',
    category: 'SEO Tools',
    categorySlug: 'seo',
    icon: 'Bot',
    slug: 'robots-txt-generator',
    tags: [],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'sitemap-gen',
    name: 'Sitemap Generator',
    description: 'Generate XML sitemap for websites',
    category: 'SEO Tools',
    categorySlug: 'seo',
    icon: 'Map',
    slug: 'sitemap-generator',
    tags: ['beta'],
    implemented: true,
    inputType: 'url',
    outputType: 'text',
  },
  {
    id: 'keyword-extractor',
    name: 'Keyword Extractor',
    description: 'Extract important keywords from any text',
    category: 'SEO Tools',
    categorySlug: 'seo',
    icon: 'Key',
    slug: 'keyword-extractor',
    tags: [],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'social-preview',
    name: 'Social Media Preview',
    description: 'Preview how URLs look on social platforms',
    category: 'SEO Tools',
    categorySlug: 'seo',
    icon: 'Eye',
    slug: 'social-media-preview',
    tags: ['new'],
    implemented: true,
    inputType: 'url',
    outputType: 'preview',
  },

  // ── CALCULATORS ────────────────────────────────────────────────────────────
  {
    id: 'age-calc',
    name: 'Age Calculator',
    description: 'Calculate exact age from date of birth',
    category: 'Calculators',
    categorySlug: 'calculator',
    icon: 'Calendar',
    slug: 'age-calculator',
    tags: ['trending'],
    popular: true,
    implemented: true,
    inputType: 'none',
    outputType: 'text',
  },
  {
    id: 'bmi-calc',
    name: 'BMI Calculator',
    description: 'Calculate Body Mass Index instantly',
    category: 'Calculators',
    categorySlug: 'calculator',
    icon: 'Activity',
    slug: 'bmi-calculator',
    tags: [],
    popular: true,
    implemented: true,
    inputType: 'none',
    outputType: 'text',
  },
  {
    id: 'emi-calc',
    name: 'EMI Calculator',
    description: 'Calculate loan EMI, interest and schedule',
    category: 'Calculators',
    categorySlug: 'calculator',
    icon: 'Banknote',
    slug: 'emi-calculator',
    tags: ['hot'],
    popular: true,
    implemented: true,
    inputType: 'none',
    outputType: 'text',
  },
  {
    id: 'currency-conv',
    name: 'Currency Converter',
    description: 'Convert between 170+ world currencies',
    category: 'Calculators',
    categorySlug: 'calculator',
    icon: 'DollarSign',
    slug: 'currency-converter',
    tags: ['trending'],
    popular: true,
    implemented: true,
    inputType: 'none',
    outputType: 'text',
  },
  {
    id: 'unit-conv',
    name: 'Unit Converter',
    description: 'Convert length, weight, temperature and more',
    category: 'Calculators',
    categorySlug: 'calculator',
    icon: 'Ruler',
    slug: 'unit-converter',
    tags: [],
    implemented: true,
    inputType: 'none',
    outputType: 'text',
  },
  {
    id: 'pct-calc',
    name: 'Percentage Calculator',
    description: 'Calculate percentages, discounts and more',
    category: 'Calculators',
    categorySlug: 'calculator',
    icon: 'Percent',
    slug: 'percentage-calculator',
    tags: [],
    implemented: true,
    inputType: 'none',
    outputType: 'text',
  },
  {
    id: 'compound-interest',
    name: 'Compound Interest',
    description: 'Calculate compound interest growth over time',
    category: 'Calculators',
    categorySlug: 'calculator',
    icon: 'TrendingUp',
    slug: 'compound-interest-calculator',
    tags: ['new'],
    implemented: true,
    inputType: 'none',
    outputType: 'text',
  },
  {
    id: 'gst-calc',
    name: 'GST Calculator',
    description: 'Calculate GST amount on products and services',
    category: 'Calculators',
    categorySlug: 'calculator',
    icon: 'Receipt',
    slug: 'gst-calculator',
    tags: ['new'],
    implemented: true,
    inputType: 'none',
    outputType: 'text',
  },
  {
    id: 'tip-calc',
    name: 'Tip Calculator',
    description: 'Calculate restaurant tip and split bills',
    category: 'Calculators',
    categorySlug: 'calculator',
    icon: 'Coffee',
    slug: 'tip-calculator',
    tags: [],
    implemented: true,
    inputType: 'none',
    outputType: 'text',
  },
  {
    id: 'date-diff',
    name: 'Date Difference',
    description: 'Calculate exact time between two dates',
    category: 'Calculators',
    categorySlug: 'calculator',
    icon: 'CalendarDays',
    slug: 'date-difference-calculator',
    tags: [],
    implemented: true,
    inputType: 'none',
    outputType: 'text',
  },
  {
    id: 'timezone-conv',
    name: 'Timezone Converter',
    description: 'Convert time across world time zones',
    category: 'Calculators',
    categorySlug: 'calculator',
    icon: 'Globe',
    slug: 'timezone-converter',
    tags: ['new'],
    implemented: true,
    inputType: 'none',
    outputType: 'text',
  },
  {
    id: 'calorie-calc',
    name: 'Calorie Calculator',
    description: 'Calculate daily calorie intake needs',
    category: 'Calculators',
    categorySlug: 'calculator',
    icon: 'Flame',
    slug: 'calorie-calculator',
    tags: ['beta'],
    implemented: true,
    inputType: 'none',
    outputType: 'text',
  },
  {
    id: 'salary-calc',
    name: 'Salary Calculator',
    description: 'Calculate net salary after tax deductions',
    category: 'Calculators',
    categorySlug: 'calculator',
    icon: 'Wallet',
    slug: 'salary-calculator',
    tags: ['new'],
    implemented: true,
    inputType: 'none',
    outputType: 'text',
  },

  // ── FILE TOOLS ─────────────────────────────────────────────────────────────
  {
    id: 'zip-creator',
    name: 'ZIP Creator',
    description: 'Compress files into ZIP archives',
    category: 'File Tools',
    categorySlug: 'file',
    icon: 'Archive',
    slug: 'zip-creator',
    tags: ['trending'],
    implemented: true,
    inputType: 'file',
    outputType: 'file',
  },
  {
    id: 'file-hash',
    name: 'File Hash Checker',
    description: 'Verify file integrity with MD5/SHA hashes',
    category: 'File Tools',
    categorySlug: 'file',
    icon: 'ShieldCheck',
    slug: 'file-hash-checker',
    tags: ['new'],
    implemented: true,
    inputType: 'file',
    outputType: 'text',
  },
  {
    id: 'file-metadata',
    name: 'File Metadata Viewer',
    description: 'View detailed metadata of any file',
    category: 'File Tools',
    categorySlug: 'file',
    icon: 'Info',
    slug: 'file-metadata-viewer',
    tags: [],
    implemented: true,
    inputType: 'file',
    outputType: 'text',
  },
  {
    id: 'binary-text',
    name: 'Binary to Text',
    description: 'Convert binary code to readable text',
    category: 'File Tools',
    categorySlug: 'file',
    icon: 'Binary',
    slug: 'binary-to-text',
    tags: [],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'text-binary',
    name: 'Text to Binary',
    description: 'Convert text to binary code',
    category: 'File Tools',
    categorySlug: 'file',
    icon: 'Code2',
    slug: 'text-to-binary',
    tags: [],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },

  // ── AI TOOLS ───────────────────────────────────────────────────────────────
  {
    id: 'ai-summarizer',
    name: 'AI Summarizer',
    description: 'Summarize long articles and documents with AI',
    category: 'AI Tools',
    categorySlug: 'ai',
    icon: 'Sparkles',
    slug: 'ai-summarizer',
    tags: ['hot', 'trending'],
    popular: true,
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'ai-paraphraser',
    name: 'AI Paraphraser',
    description: 'Rephrase content in different styles',
    category: 'AI Tools',
    categorySlug: 'ai',
    icon: 'RefreshCcw',
    slug: 'ai-paraphraser',
    tags: ['trending'],
    popular: true,
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'ai-grammar',
    name: 'Grammar Checker',
    description: 'AI-powered grammar and writing improvement',
    category: 'AI Tools',
    categorySlug: 'ai',
    icon: 'CheckCircle',
    slug: 'grammar-checker',
    tags: ['hot'],
    popular: true,
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'ai-translator',
    name: 'AI Translator',
    description: 'Translate text between 100+ languages',
    category: 'AI Tools',
    categorySlug: 'ai',
    icon: 'Languages',
    slug: 'ai-translator',
    tags: ['trending'],
    popular: true,
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'ai-code-gen',
    name: 'AI Code Generator',
    description: 'Generate code in any programming language',
    category: 'AI Tools',
    categorySlug: 'ai',
    icon: 'Terminal',
    slug: 'ai-code-generator',
    tags: ['hot', 'new'],
    popular: true,
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'ai-email',
    name: 'AI Email Writer',
    description: 'Write professional emails in seconds',
    category: 'AI Tools',
    categorySlug: 'ai',
    icon: 'Mail',
    slug: 'ai-email-writer',
    tags: ['new'],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'ai-seo-writer',
    name: 'AI SEO Writer',
    description: 'Write SEO-optimized blog posts and articles',
    category: 'AI Tools',
    categorySlug: 'ai',
    icon: 'PenLine',
    slug: 'ai-seo-writer',
    tags: ['new', 'beta'],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'ai-hashtag',
    name: 'Hashtag Generator',
    description: 'Generate trending hashtags for social media',
    category: 'AI Tools',
    categorySlug: 'ai',
    icon: 'Hash',
    slug: 'hashtag-generator',
    tags: ['trending'],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'ai-image-gen',
    name: 'AI Image Generator',
    description: 'Generate stunning images from text prompts',
    category: 'AI Tools',
    categorySlug: 'ai',
    icon: 'ImagePlus',
    slug: 'ai-image-generator',
    tags: ['hot', 'trending', 'new'],
    popular: true,
    implemented: true,
    inputType: 'text',
    outputType: 'file',
  },
  {
    id: 'ai-resume',
    name: 'AI Resume Builder',
    description: 'Create professional resumes with AI help',
    category: 'AI Tools',
    categorySlug: 'ai',
    icon: 'FileBadge2',
    slug: 'ai-resume-builder',
    tags: ['new'],
    implemented: true,
    inputType: 'text',
    outputType: 'file',
  },
  {
    id: 'ai-cover-letter',
    name: 'Cover Letter Writer',
    description: 'Write compelling cover letters with AI',
    category: 'AI Tools',
    categorySlug: 'ai',
    icon: 'ClipboardEdit',
    slug: 'ai-cover-letter',
    tags: ['new'],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
]

const ACTIVE_TOOL_SLUGS = new Set(
  ALL_TOOLS.filter(tool => tool.implemented).map(tool => tool.slug)
)

export const TOOLS: Tool[] = ALL_TOOLS.filter(tool => ACTIVE_TOOL_SLUGS.has(tool.slug))
export const ACTIVE_CATEGORIES = CATEGORIES.filter(category => TOOLS.some(tool => tool.categorySlug === category.slug))

export const TRENDING_TOOLS = [
  ...TOOLS.filter(t => t.slug === 'all-in-one-video-downloader'),
  ...TOOLS.filter(t => (t.tags.includes('trending') || t.popular) && t.slug !== 'all-in-one-video-downloader'),
].slice(0, 12)
export const NEW_TOOLS = TOOLS.filter(t => t.tags.includes('new')).slice(0, 12)

export function getToolsByCategory(slug: string): Tool[] {
  return TOOLS.filter(t => t.categorySlug === slug)
}

export function getToolBySlug(slug: string): Tool | undefined {
  return TOOLS.find(t => t.slug === slug)
}

export function searchTools(query: string): Tool[] {
  const q = query.toLowerCase()
  return TOOLS.filter(
    t =>
      t.name.toLowerCase().includes(q) ||
      t.description.toLowerCase().includes(q) ||
      t.category.toLowerCase().includes(q)
  )
}
