export type ToolTag = 'new' | 'trending' | 'beta' | 'hot' | 'free'

export interface Tool {
  id: string
  name: string
  description: string
  category: string
  categorySlug: string
  icon: string
  slug: string
  tags: ToolTag[]
  popular?: boolean
  implemented: boolean
  enabled?: boolean
  inputType?: 'file' | 'text' | 'url' | 'both' | 'none'
  outputType?: 'file' | 'text' | 'preview' | 'both'
  acceptedFormats?: string[]
  createdAt?: string
  updatedAt?: string
}

export interface Category {
  id: string
  name: string
  slug: string
  description: string
  icon: string
  color: string
  gradient: string
  toolCount?: number
}

export const CATEGORIES: Category[] = [
  {
    id: 'pdf',
    name: 'PDF Tools',
    slug: 'pdf',
    description: 'Convert, compress, merge and edit PDF files',
    icon: 'FileText',
    color: 'red',
    gradient: 'from-red-500 to-orange-500',
  },
  {
    id: 'image',
    name: 'Image Tools',
    slug: 'image',
    description: 'Resize, compress, convert and edit images',
    icon: 'Image',
    color: 'blue',
    gradient: 'from-blue-500 to-cyan-500',
  },
  {
    id: 'video',
    name: 'Video Tools',
    slug: 'video',
    description: 'Convert, compress and edit videos',
    icon: 'Video',
    color: 'purple',
    gradient: 'from-purple-500 to-pink-500',
  },
  {
    id: 'audio',
    name: 'Audio Tools',
    slug: 'audio',
    description: 'Convert, edit and process audio files',
    icon: 'Music',
    color: 'green',
    gradient: 'from-green-500 to-teal-500',
  },
  {
    id: 'text',
    name: 'Text Tools',
    slug: 'text',
    description: 'Format, convert and analyze text content',
    icon: 'Type',
    color: 'yellow',
    gradient: 'from-yellow-500 to-amber-500',
  },
  {
    id: 'dev',
    name: 'Dev Tools',
    slug: 'dev',
    description: 'JSON, Base64, regex and developer utilities',
    icon: 'Code',
    color: 'slate',
    gradient: 'from-slate-600 to-slate-800',
  },
  {
    id: 'seo',
    name: 'SEO Tools',
    slug: 'seo',
    description: 'Meta tags, keywords and SEO analysis',
    icon: 'Search',
    color: 'indigo',
    gradient: 'from-indigo-500 to-blue-600',
  },
  {
    id: 'calculator',
    name: 'Calculators',
    slug: 'calculator',
    description: 'EMI, currency, BMI and more calculators',
    icon: 'Calculator',
    color: 'teal',
    gradient: 'from-teal-500 to-emerald-500',
  },
  {
    id: 'file',
    name: 'File Tools',
    slug: 'file',
    description: 'Compress, extract and manage files',
    icon: 'Folder',
    color: 'orange',
    gradient: 'from-orange-500 to-yellow-500',
  },
]

const ALL_TOOLS: Tool[] = [
  // ── PDF TOOLS ──────────────────────────────────────────────────────────────
  {
    id: 'pdf-merge',
    name: 'Merge PDF Files',
    description: 'Combine multiple PDF files into one for easier sharing and organized printing',
    category: 'PDF Tools',
    categorySlug: 'pdf',
    icon: 'Combine',
    slug: 'merge-pdf',
    tags: ['trending'],
    popular: true,
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.pdf'],
  },
  {
    id: 'pdf-split',
    name: 'Split PDF Pages',
    description: 'Split PDF into separate pages or ranges for selective emailing or extraction',
    category: 'PDF Tools',
    categorySlug: 'pdf',
    icon: 'Scissors',
    slug: 'split-pdf',
    tags: ['trending'],
    popular: true,
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.pdf'],
  },
  {
    id: 'pdf-compress',
    name: 'Compress PDF for Email & Web',
    description: 'Shrink PDF size for email, chat, or faster web uploads without losing quality',
    category: 'PDF Tools',
    categorySlug: 'pdf',
    icon: 'Minimize2',
    slug: 'compress-pdf',
    tags: ['hot'],
    popular: true,
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.pdf'],
  },
  {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    description: 'Convert PDF documents to editable Word files',
    category: 'PDF Tools',
    categorySlug: 'pdf',
    icon: 'FileType',
    slug: 'pdf-to-word',
    tags: ['trending'],
    popular: true,
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.pdf'],
  },
  {
    id: 'pdf-to-excel',
    name: 'PDF to Excel',
    description: 'Extract table data from PDF files into Excel workbooks',
    category: 'PDF Tools',
    categorySlug: 'pdf',
    icon: 'Table2',
    slug: 'pdf-to-excel',
    tags: ['trending', 'new'],
    popular: true,
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.pdf'],
  },
  {
    id: 'pdf-to-jpg',
    name: 'PDF to JPG',
    description: 'Convert PDF pages to JPG images',
    category: 'PDF Tools',
    categorySlug: 'pdf',
    icon: 'Image',
    slug: 'pdf-to-jpg',
    tags: ['new'],
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.pdf'],
  },
  {
    id: 'pdf-ocr',
    name: 'PDF OCR',
    description: 'Extract readable text from scanned PDF files',
    category: 'PDF Tools',
    categorySlug: 'pdf',
    icon: 'ScanText',
    slug: 'pdf-ocr',
    tags: ['hot', 'trending'],
    popular: true,
    implemented: true,
    inputType: 'file',
    outputType: 'text',
    acceptedFormats: ['.pdf'],
  },
  {
    id: 'jpg-to-pdf',
    name: 'JPG to PDF',
    description: 'Convert JPG images to PDF format',
    category: 'PDF Tools',
    categorySlug: 'pdf',
    icon: 'FilePlus',
    slug: 'jpg-to-pdf',
    tags: ['new'],
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp'],
  },
  {
    id: 'pdf-unlock',
    name: 'Unlock PDF',
    description: 'Remove password and restrictions from PDF files for quick editing and printing',
    category: 'PDF Tools',
    categorySlug: 'pdf',
    icon: 'Unlock',
    slug: 'unlock-pdf',
    tags: [],
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.pdf'],
  },
  {
    id: 'word-to-pdf',
    name: 'Word to PDF',
    description: 'Convert Word DOCX files to PDF',
    category: 'PDF Tools',
    categorySlug: 'pdf',
    icon: 'FileOutput',
    slug: 'word-to-pdf',
    tags: ['trending'],
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.docx', '.doc'],
  },
  {
    id: 'pdf-translator',
    name: 'PDF Translator',
    description: 'Translate PDF content into another language',
    category: 'PDF Tools',
    categorySlug: 'pdf',
    icon: 'Languages',
    slug: 'pdf-translator',
    tags: ['new', 'trending'],
    popular: true,
    implemented: true,
    inputType: 'file',
    outputType: 'text',
    acceptedFormats: ['.pdf'],
  },
  {
    id: 'pdf-summarizer',
    name: 'PDF Summarizer',
    description: 'Generate short or detailed summaries from PDF files',
    category: 'PDF Tools',
    categorySlug: 'pdf',
    icon: 'Sparkles',
    slug: 'pdf-summarizer',
    tags: ['hot', 'trending'],
    popular: true,
    implemented: true,
    inputType: 'file',
    outputType: 'text',
    acceptedFormats: ['.pdf'],
  },

  // ── IMAGE TOOLS ────────────────────────────────────────────────────────────
  {
    id: 'image-compress',
    name: 'Compress Image',
    description: 'Reduce image size for faster web loading, email, and chat sharing',
    category: 'Image Tools',
    categorySlug: 'image',
    icon: 'ImageDown',
    slug: 'compress-image',
    tags: ['hot'],
    popular: true,
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp'],
  },
  {
    id: 'image-resize',
    name: 'Resize Image',
    description: 'Resize images for Instagram, Facebook, and professional profile dimensions',
    category: 'Image Tools',
    categorySlug: 'image',
    icon: 'Maximize2',
    slug: 'resize-image',
    tags: ['trending'],
    popular: true,
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp', '.gif'],
  },
  {
    id: 'image-convert',
    name: 'Convert Image',
    description: 'Convert images between JPG, PNG, WebP formats',
    category: 'Image Tools',
    categorySlug: 'image',
    icon: 'RefreshCw',
    slug: 'convert-image',
    tags: ['new'],
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp', '.gif', '.bmp'],
  },
  {
    id: 'image-crop',
    name: 'Crop Image',
    description: 'Crop images to custom sizes or aspect ratios',
    category: 'Image Tools',
    categorySlug: 'image',
    icon: 'Crop',
    slug: 'crop-image',
    tags: [],
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp'],
  },
  {
    id: 'bg-remover',
    name: 'Remove Background',
    description: 'Remove backgrounds for professional product shots and profile pictures',
    category: 'Image Tools',
    categorySlug: 'image',
    icon: 'Eraser',
    slug: 'remove-background',
    tags: ['hot', 'trending'],
    popular: true,
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp'],
  },
  {
    id: 'passport-photo-maker',
    name: 'Passport Photo Maker',
    description: 'Create official-size passport and ID photos with clean backgrounds for printing',
    category: 'Image Tools',
    categorySlug: 'image',
    icon: 'FileUser',
    slug: 'passport-photo-maker',
    tags: ['new', 'hot'],
    popular: true,
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp'],
  },
  {
    id: 'blur-background',
    name: 'Blur Background',
    description: 'Keep the subject sharp and blur the background for portraits',
    category: 'Image Tools',
    categorySlug: 'image',
    icon: 'Aperture',
    slug: 'blur-background',
    tags: ['new', 'trending'],
    popular: true,
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp'],
  },
  {
    id: 'image-to-text',
    name: 'Image to Text (OCR)',
    description: 'Extract text from images using OCR',
    category: 'Image Tools',
    categorySlug: 'image',
    icon: 'ScanText',
    slug: 'image-to-text',
    tags: ['trending'],
    implemented: true,
    inputType: 'file',
    outputType: 'text',
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp'],
  },
  {
    id: 'qr-generate',
    name: 'QR Code Generator',
    description: 'Generate QR codes for URLs, text and more',
    category: 'Image Tools',
    categorySlug: 'image',
    icon: 'QrCode',
    slug: 'qr-code-generator',
    tags: ['trending'],
    popular: true,
    implemented: true,
    inputType: 'text',
    outputType: 'file',
  },
  {
    id: 'palette-gen',
    name: 'Color Palette Generator',
    description: 'Generate beautiful color palettes from images',
    category: 'Image Tools',
    categorySlug: 'image',
    icon: 'Palette',
    slug: 'color-palette-generator',
    tags: ['new'],
    implemented: true,
    inputType: 'both',
    outputType: 'text',
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp'],
  },
  {
    id: 'image-to-pdf',
    name: 'Image to PDF',
    description: 'Convert multiple images into a polished PDF document',
    category: 'Image Tools',
    categorySlug: 'image',
    icon: 'FileImage',
    slug: 'image-to-pdf',
    tags: ['new'],
    popular: true,
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp'],
  },
  {
    id: 'image-upscaler',
    name: 'Image Upscaler',
    description: 'Upscale images with sharper edges and cleaner detail',
    category: 'Image Tools',
    categorySlug: 'image',
    icon: 'ScanSearch',
    slug: 'image-upscaler',
    tags: ['new', 'trending'],
    popular: true,
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp'],
  },

  // ── VIDEO TOOLS ────────────────────────────────────────────────────────────
  {
    id: 'all-in-one-video-downloader',
    name: 'All-in-One Video Downloader',
    description: 'Download MP4, WEBM, MP3, M4A and HD thumbnails from supported video links',
    category: 'Video Tools',
    categorySlug: 'video',
    icon: 'Download',
    slug: 'all-in-one-video-downloader',
    tags: ['trending', 'hot'],
    popular: true,
    implemented: true,
    inputType: 'url',
    outputType: 'file',
  },
  {
    id: 'video-compress',
    name: 'Compress Video',
    description: 'Make videos smaller for chat, Discord, and email sharing with MP4 compression',
    category: 'Video Tools',
    categorySlug: 'video',
    icon: 'Film',
    slug: 'compress-video',
    tags: ['trending'],
    popular: true,
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.mp4', '.avi', '.mov', '.mkv', '.webm'],
  },
  {
    id: 'video-to-mp3',
    name: 'Video to MP3',
    description: 'Extract high-quality audio MP3 from videos for ringtones or podcast use',
    category: 'Video Tools',
    categorySlug: 'video',
    icon: 'Music',
    slug: 'video-to-mp3',
    tags: ['hot'],
    popular: true,
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.mp4', '.avi', '.mov', '.mkv', '.webm'],
  },
  {
    id: 'video-trim',
    name: 'Trim Video',
    description: 'Cut and trim video clips easily',
    category: 'Video Tools',
    categorySlug: 'video',
    icon: 'Scissors',
    slug: 'trim-video',
    tags: [],
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.mp4', '.avi', '.mov', '.webm'],
  },
  {
    id: 'video-to-gif',
    name: 'Video to GIF',
    description: 'Create animated GIFs for Slack, Discord, and Social Media from your video clips',
    category: 'Video Tools',
    categorySlug: 'video',
    icon: 'Clapperboard',
    slug: 'video-to-gif',
    tags: ['trending', 'new'],
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.mp4', '.avi', '.mov', '.webm'],
  },
  {
    id: 'yt-thumbnail',
    name: 'YT Thumbnail Downloader',
    description: 'Download YouTube video thumbnails',
    category: 'Video Tools',
    categorySlug: 'video',
    icon: 'Download',
    slug: 'youtube-thumbnail-downloader',
    tags: ['hot'],
    popular: true,
    implemented: true,
    inputType: 'url',
    outputType: 'file',
  },
  {
    id: 'video-speed',
    name: 'Change Video Speed',
    description: 'Speed up or slow down video playback',
    category: 'Video Tools',
    categorySlug: 'video',
    icon: 'Gauge',
    slug: 'change-video-speed',
    tags: ['beta'],
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.mp4', '.webm', '.mov'],
  },
  {
    id: 'video-mute',
    name: 'Mute Video',
    description: 'Remove audio track from video files',
    category: 'Video Tools',
    categorySlug: 'video',
    icon: 'VolumeX',
    slug: 'mute-video',
    tags: [],
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.mp4', '.avi', '.mov', '.webm'],
  },
  {
    id: 'video-merge',
    name: 'Merge Video',
    description: 'Combine multiple video clips into one clean export',
    category: 'Video Tools',
    categorySlug: 'video',
    icon: 'Combine',
    slug: 'merge-video',
    tags: ['new', 'trending'],
    popular: true,
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.mp4', '.mov', '.mkv', '.webm'],
  },
  {
    id: 'video-rotate',
    name: 'Rotate Video',
    description: 'Rotate or flip video orientation before export',
    category: 'Video Tools',
    categorySlug: 'video',
    icon: 'RotateCw',
    slug: 'rotate-video',
    tags: ['new'],
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.mp4', '.mov', '.mkv', '.webm'],
  },
  {
    id: 'video-subtitles',
    name: 'Add Subtitles',
    description: 'Burn subtitle files or SRT text into a video export',
    category: 'Video Tools',
    categorySlug: 'video',
    icon: 'Captions',
    slug: 'add-subtitles',
    tags: ['new', 'trending'],
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.mp4', '.mov', '.mkv', '.webm'],
  },
  {
    id: 'gif-maker',
    name: 'GIF Maker',
    description: 'Create animated GIFs from images',
    category: 'Video Tools',
    categorySlug: 'video',
    icon: 'Play',
    slug: 'gif-maker',
    tags: ['new'],
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp'],
  },

  // ── AUDIO TOOLS ────────────────────────────────────────────────────────────
  {
    id: 'audio-convert',
    name: 'Audio Converter',
    description: 'Convert audio files between common studio and playback formats',
    category: 'Audio Tools',
    categorySlug: 'audio',
    icon: 'AudioWaveform',
    slug: 'convert-audio',
    tags: [],
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.mp3', '.wav', '.aac', '.flac', '.ogg'],
  },
  {
    id: 'audio-trim',
    name: 'Audio Cutter',
    description: 'Trim audio clips to the exact range you want',
    category: 'Audio Tools',
    categorySlug: 'audio',
    icon: 'Scissors',
    slug: 'trim-audio',
    tags: [],
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.mp3', '.wav', '.ogg', '.aac'],
  },
  {
    id: 'tts',
    name: 'Text to Speech',
    description: 'Generate a playable voice file from text',
    category: 'Audio Tools',
    categorySlug: 'audio',
    icon: 'Mic',
    slug: 'audio-text-to-speech',
    tags: ['trending', 'hot'],
    popular: true,
    implemented: true,
    inputType: 'text',
    outputType: 'file',
  },
  {
    id: 'stt',
    name: 'Audio to Text',
    description: 'Transcribe spoken audio into readable text',
    category: 'Audio Tools',
    categorySlug: 'audio',
    icon: 'MicOff',
    slug: 'speech-to-text',
    tags: ['trending'],
    implemented: true,
    inputType: 'file',
    outputType: 'text',
    acceptedFormats: ['.mp3', '.wav', '.ogg', '.m4a'],
  },
  {
    id: 'audio-merge',
    name: 'Merge Audio',
    description: 'Combine multiple audio files into one final track',
    category: 'Audio Tools',
    categorySlug: 'audio',
    icon: 'Combine',
    slug: 'merge-audio',
    tags: [],
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.mp3', '.wav', '.ogg'],
  },
  {
    id: 'audio-compress',
    name: 'Audio Compressor',
    description: 'Reduce audio file size with cleaner compression presets',
    category: 'Audio Tools',
    categorySlug: 'audio',
    icon: 'Minimize2',
    slug: 'compress-audio',
    tags: [],
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.mp3', '.wav', '.flac'],
  },
  {
    id: 'audio-recorder',
    name: 'Audio Recorder',
    description: 'Record audio directly in your browser',
    category: 'Audio Tools',
    categorySlug: 'audio',
    icon: 'Mic2',
    slug: 'audio-recorder',
    tags: ['new'],
    implemented: true,
    inputType: 'none',
    outputType: 'file',
  },
  {
    id: 'bpm-detector',
    name: 'BPM Detector',
    description: 'Detect beats per minute of audio tracks',
    category: 'Audio Tools',
    categorySlug: 'audio',
    icon: 'Activity',
    slug: 'bpm-detector',
    tags: ['beta'],
    implemented: true,
    inputType: 'file',
    outputType: 'text',
    acceptedFormats: ['.mp3', '.wav', '.ogg'],
  },
  {
    id: 'audio-eq',
    name: 'Audio Equalizer',
    description: 'Apply quick EQ presets for bass, treble, and voice clarity',
    category: 'Audio Tools',
    categorySlug: 'audio',
    icon: 'SlidersHorizontal',
    slug: 'audio-equalizer',
    tags: ['new'],
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.mp3', '.wav', '.flac', '.m4a', '.ogg'],
  },
  {
    id: 'audio-metadata',
    name: 'Audio Metadata Editor',
    description: 'Edit title, artist, album, and year before export',
    category: 'Audio Tools',
    categorySlug: 'audio',
    icon: 'Tags',
    slug: 'audio-metadata-editor',
    tags: ['new'],
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.mp3', '.wav', '.flac', '.m4a', '.ogg'],
  },
  {
    id: 'audio-speed',
    name: 'Change Audio Speed',
    description: 'Speed up or slow down audio while keeping it export-ready',
    category: 'Audio Tools',
    categorySlug: 'audio',
    icon: 'Gauge',
    slug: 'change-audio-speed',
    tags: ['new'],
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.mp3', '.wav', '.flac', '.m4a', '.ogg'],
  },
  {
    id: 'audio-vocals',
    name: 'Remove Vocals',
    description: 'Reduce centered vocal content and export an instrumental-focused file',
    category: 'Audio Tools',
    categorySlug: 'audio',
    icon: 'MicOff',
    slug: 'remove-vocals',
    tags: ['new'],
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.mp3', '.wav', '.m4a', '.ogg'],
  },
  {
    id: 'audio-silence',
    name: 'Trim Silence',
    description: 'Remove quiet pauses from recorded audio',
    category: 'Audio Tools',
    categorySlug: 'audio',
    icon: 'Waveform',
    slug: 'trim-silence',
    tags: ['new'],
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.mp3', '.wav', '.m4a', '.ogg'],
  },
  {
    id: 'audio-volume',
    name: 'Volume Booster',
    description: 'Increase overall loudness with a simple gain boost',
    category: 'Audio Tools',
    categorySlug: 'audio',
    icon: 'Volume2',
    slug: 'volume-booster',
    tags: ['new'],
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.mp3', '.wav', '.flac', '.m4a', '.ogg'],
  },

  // ── TEXT TOOLS ─────────────────────────────────────────────────────────────
  {
    id: 'word-counter',
    name: 'Word Counter',
    description: 'Count words, characters, and reading structure',
    category: 'Text Tools',
    categorySlug: 'text',
    icon: 'AlignLeft',
    slug: 'word-counter',
    tags: ['trending'],
    popular: true,
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'case-converter',
    name: 'Case Converter',
    description: 'Convert text into uppercase, title case, and more',
    category: 'Text Tools',
    categorySlug: 'text',
    icon: 'CaseUpper',
    slug: 'text-case-converter',
    tags: [],
    popular: true,
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'lorem-ipsum',
    name: 'Lorem Ipsum Generator',
    description: 'Generate placeholder lorem ipsum text',
    category: 'Text Tools',
    categorySlug: 'text',
    icon: 'FileText',
    slug: 'lorem-ipsum-generator',
    tags: [],
    implemented: true,
    inputType: 'none',
    outputType: 'text',
  },
  {
    id: 'text-diff',
    name: 'Text Compare',
    description: 'Compare two versions of text and review differences',
    category: 'Text Tools',
    categorySlug: 'text',
    icon: 'GitCompare',
    slug: 'text-diff-checker',
    tags: ['new'],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'duplicate-remover',
    name: 'Duplicate Text Remover',
    description: 'Remove repeated lines and keep only unique text rows',
    category: 'Text Tools',
    categorySlug: 'text',
    icon: 'Filter',
    slug: 'remove-duplicate-lines',
    tags: [],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'text-reverser',
    name: 'Text Reverser',
    description: 'Reverse words or characters in text',
    category: 'Text Tools',
    categorySlug: 'text',
    icon: 'FlipHorizontal',
    slug: 'text-reverser',
    tags: [],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'md-to-html',
    name: 'Markdown to HTML',
    description: 'Convert Markdown text to HTML markup',
    category: 'Text Tools',
    categorySlug: 'text',
    icon: 'Code',
    slug: 'markdown-to-html',
    tags: ['new'],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'csv-to-json',
    name: 'CSV to JSON',
    description: 'Convert CSV data to JSON format',
    category: 'Text Tools',
    categorySlug: 'text',
    icon: 'Table',
    slug: 'csv-to-json',
    tags: [],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'json-to-csv',
    name: 'JSON to CSV',
    description: 'Convert JSON arrays to CSV spreadsheet',
    category: 'Text Tools',
    categorySlug: 'text',
    icon: 'Table2',
    slug: 'json-to-csv',
    tags: [],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'string-extractor',
    name: 'String Extractor',
    description: 'Extract URLs, emails, and patterns from text',
    category: 'Text Tools',
    categorySlug: 'text',
    icon: 'Magnet',
    slug: 'string-extractor',
    tags: ['beta'],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'readability',
    name: 'Readability Score',
    description: 'Analyze text readability and grade level',
    category: 'Text Tools',
    categorySlug: 'text',
    icon: 'BookOpen',
    slug: 'readability-score',
    tags: ['new'],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'keyword-density',
    name: 'Keyword Density',
    description: 'Analyze keyword frequency in your content',
    category: 'Text Tools',
    categorySlug: 'text',
    icon: 'BarChart',
    slug: 'keyword-density',
    tags: [],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'text-ai-generator',
    name: 'AI Text Generator',
    description: 'Generate polished first drafts from a short prompt',
    category: 'Text Tools',
    categorySlug: 'text',
    icon: 'Sparkles',
    slug: 'ai-text-generator',
    tags: ['trending', 'new'],
    popular: true,
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'text-grammar',
    name: 'Grammar Checker',
    description: 'Review grammar and clarity before you publish or share',
    category: 'Text Tools',
    categorySlug: 'text',
    icon: 'SpellCheck',
    slug: 'text-grammar-checker',
    tags: ['trending'],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'text-paraphrase',
    name: 'Paraphrasing Tool',
    description: 'Rewrite text into cleaner alternate phrasing',
    category: 'Text Tools',
    categorySlug: 'text',
    icon: 'Replace',
    slug: 'paraphrasing-tool',
    tags: ['new'],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'text-plagiarism',
    name: 'Plagiarism Checker',
    description: 'Review originality signals and repeated phrase clusters',
    category: 'Text Tools',
    categorySlug: 'text',
    icon: 'ShieldAlert',
    slug: 'plagiarism-checker',
    tags: ['new'],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'text-stt',
    name: 'Speech to Text',
    description: 'Upload voice files and turn spoken words into text',
    category: 'Text Tools',
    categorySlug: 'text',
    icon: 'MicOff',
    slug: 'text-speech-to-text',
    tags: ['trending'],
    implemented: true,
    inputType: 'file',
    outputType: 'text',
    acceptedFormats: ['.mp3', '.wav', '.ogg', '.m4a'],
  },
  {
    id: 'text-summary',
    name: 'Text Summarizer',
    description: 'Summarize long content into short, detailed, or bullet formats',
    category: 'Text Tools',
    categorySlug: 'text',
    icon: 'FileText',
    slug: 'text-summarizer',
    tags: ['trending', 'hot'],
    popular: true,
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'text-tts',
    name: 'Text to Speech',
    description: 'Convert written text into a playable voice file',
    category: 'Text Tools',
    categorySlug: 'text',
    icon: 'Mic',
    slug: 'text-to-speech',
    tags: ['trending'],
    implemented: true,
    inputType: 'text',
    outputType: 'file',
  },
  {
    id: 'text-url',
    name: 'URL Encoder / Decoder',
    description: 'Encode and decode URL-safe text from one compact panel',
    category: 'Text Tools',
    categorySlug: 'text',
    icon: 'Link',
    slug: 'text-url-encoder-decoder',
    tags: ['new'],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },

  // ── DEV TOOLS ──────────────────────────────────────────────────────────────
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Format, validate and beautify JSON data',
    category: 'Dev Tools',
    categorySlug: 'dev',
    icon: 'Braces',
    slug: 'json-formatter',
    tags: ['hot'],
    popular: true,
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'base64',
    name: 'Base64 Encoder/Decoder',
    description: 'Encode and decode Base64 strings instantly',
    category: 'Dev Tools',
    categorySlug: 'dev',
    icon: 'Binary',
    slug: 'base64-encoder-decoder',
    tags: [],
    popular: true,
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'url-encoder',
    name: 'URL Encoder/Decoder',
    description: 'Encode and decode URL components',
    category: 'Dev Tools',
    categorySlug: 'dev',
    icon: 'Link',
    slug: 'url-encoder-decoder',
    tags: [],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder & Debugger',
    description: 'Decode and inspect JWT token payloads to debug authentication and security claims',
    category: 'Dev Tools',
    categorySlug: 'dev',
    icon: 'KeyRound',
    slug: 'jwt-decoder',
    tags: ['trending'],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'uuid-gen',
    name: 'UUID Generator',
    description: 'Generate unique UUIDs and GUIDs',
    category: 'Dev Tools',
    categorySlug: 'dev',
    icon: 'Hash',
    slug: 'uuid-generator',
    tags: [],
    implemented: true,
    inputType: 'none',
    outputType: 'text',
  },
  {
    id: 'hash-gen',
    name: 'Hash Generator',
    description: 'Generate MD5, SHA-1, SHA-256 hashes',
    category: 'Dev Tools',
    categorySlug: 'dev',
    icon: 'Shield',
    slug: 'hash-generator',
    tags: [],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test and debug regular expressions live',
    category: 'Dev Tools',
    categorySlug: 'dev',
    icon: 'Regex',
    slug: 'regex-tester',
    tags: ['trending'],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'css-minifier',
    name: 'CSS Minifier',
    description: 'Minify CSS code to reduce file size',
    category: 'Dev Tools',
    categorySlug: 'dev',
    icon: 'Minimize',
    slug: 'css-minifier',
    tags: [],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'js-minifier',
    name: 'JS Minifier',
    description: 'Minify JavaScript code for production',
    category: 'Dev Tools',
    categorySlug: 'dev',
    icon: 'Zap',
    slug: 'js-minifier',
    tags: [],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'color-converter',
    name: 'Color Converter',
    description: 'Convert HEX, RGB, HSL color formats',
    category: 'Dev Tools',
    categorySlug: 'dev',
    icon: 'Palette',
    slug: 'color-converter',
    tags: ['new'],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'gradient-gen',
    name: 'Gradient Generator',
    description: 'Create and export CSS gradients visually',
    category: 'Dev Tools',
    categorySlug: 'dev',
    icon: 'Paintbrush',
    slug: 'gradient-generator',
    tags: ['new'],
    implemented: true,
    inputType: 'none',
    outputType: 'text',
  },
  {
    id: 'cron-gen',
    name: 'Cron Expression Generator',
    description: 'Build and explain cron job expressions',
    category: 'Dev Tools',
    categorySlug: 'dev',
    icon: 'Clock',
    slug: 'cron-generator',
    tags: ['beta'],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'gitignore-gen',
    name: '.gitignore Generator',
    description: 'Generate .gitignore for any tech stack',
    category: 'Dev Tools',
    categorySlug: 'dev',
    icon: 'GitBranch',
    slug: 'gitignore-generator',
    tags: ['new'],
    implemented: true,
    inputType: 'none',
    outputType: 'text',
  },
  {
    id: 'api-tester',
    name: 'API Tester',
    description: 'Test REST APIs with custom headers and body',
    category: 'Dev Tools',
    categorySlug: 'dev',
    icon: 'Globe',
    slug: 'api-tester',
    tags: ['beta'],
    implemented: true,
    inputType: 'url',
    outputType: 'text',
  },
  {
    id: 'dev-code-formatter',
    name: 'Code Formatter',
    description: 'Reformat raw code into a cleaner readable block',
    category: 'Dev Tools',
    categorySlug: 'dev',
    icon: 'Code2',
    slug: 'code-formatter',
    tags: ['new'],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'dev-html-previewer',
    name: 'HTML Previewer',
    description: 'Preview markup inside a live render panel',
    category: 'Dev Tools',
    categorySlug: 'dev',
    icon: 'Eye',
    slug: 'html-previewer',
    tags: ['new'],
    implemented: true,
    inputType: 'text',
    outputType: 'preview',
  },
  {
    id: 'dev-sql-formatter',
    name: 'SQL Formatter & Beautifier',
    description: 'Format raw SQL queries into clean, readable blocks for database debugging and documentation',
    category: 'Dev Tools',
    categorySlug: 'dev',
    icon: 'Database',
    slug: 'sql-formatter',
    tags: ['new'],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },

  // ── SEO TOOLS ──────────────────────────────────────────────────────────────
  {
    id: 'meta-tag-gen',
    name: 'Meta Tag Generator',
    description: 'Generate SEO meta tags for any webpage',
    category: 'SEO Tools',
    categorySlug: 'seo',
    icon: 'Tags',
    slug: 'meta-tag-generator',
    tags: ['trending'],
    popular: true,
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'og-gen',
    name: 'Open Graph Generator',
    description: 'Generate Open Graph social preview tags',
    category: 'SEO Tools',
    categorySlug: 'seo',
    icon: 'Share2',
    slug: 'open-graph-generator',
    tags: ['new'],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'robots-txt-gen',
    name: 'Robots.txt Generator',
    description: 'Generate robots.txt for search engines',
    category: 'SEO Tools',
    categorySlug: 'seo',
    icon: 'Bot',
    slug: 'robots-txt-generator',
    tags: [],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'sitemap-gen',
    name: 'Sitemap Generator',
    description: 'Generate XML sitemap for websites',
    category: 'SEO Tools',
    categorySlug: 'seo',
    icon: 'Map',
    slug: 'sitemap-generator',
    tags: ['beta'],
    implemented: true,
    inputType: 'url',
    outputType: 'text',
  },
  {
    id: 'keyword-extractor',
    name: 'Keyword Extractor',
    description: 'Extract important keywords from any text',
    category: 'SEO Tools',
    categorySlug: 'seo',
    icon: 'Key',
    slug: 'keyword-extractor',
    tags: [],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'social-preview',
    name: 'Social Media Preview',
    description: 'Preview how URLs look on social platforms',
    category: 'SEO Tools',
    categorySlug: 'seo',
    icon: 'Eye',
    slug: 'social-media-preview',
    tags: ['new'],
    implemented: true,
    inputType: 'url',
    outputType: 'preview',
  },
  {
    id: 'seo-backlink',
    name: 'Backlink Checker',
    description: 'Review backlink-style outreach and anchor opportunities',
    category: 'SEO Tools',
    categorySlug: 'seo',
    icon: 'Link2',
    slug: 'backlink-checker',
    tags: ['new'],
    implemented: true,
    inputType: 'url',
    outputType: 'text',
  },
  {
    id: 'seo-broken-links',
    name: 'Broken Link Checker',
    description: 'Review crawl-risk signals and broken-link fix priorities',
    category: 'SEO Tools',
    categorySlug: 'seo',
    icon: 'Unlink',
    slug: 'broken-link-checker',
    tags: ['new'],
    implemented: true,
    inputType: 'url',
    outputType: 'text',
  },
  {
    id: 'seo-domain-authority',
    name: 'Domain Authority Checker',
    description: 'Review trust-style signals around a URL or hostname',
    category: 'SEO Tools',
    categorySlug: 'seo',
    icon: 'BadgeCheck',
    slug: 'domain-authority-checker',
    tags: ['new'],
    implemented: true,
    inputType: 'url',
    outputType: 'text',
  },
  {
    id: 'seo-image-checker',
    name: 'Image SEO Checker',
    description: 'Review image naming, alt text, and asset SEO basics',
    category: 'SEO Tools',
    categorySlug: 'seo',
    icon: 'Image',
    slug: 'image-seo-checker',
    tags: ['new'],
    implemented: true,
    inputType: 'url',
    outputType: 'text',
  },
  {
    id: 'seo-keywords',
    name: 'Keyword Generator',
    description: 'Generate seed keywords and long-tail topic ideas',
    category: 'SEO Tools',
    categorySlug: 'seo',
    icon: 'KeyRound',
    slug: 'keyword-generator',
    tags: ['trending'],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'seo-speed',
    name: 'Page Speed Checker',
    description: 'Review speed-oriented delivery signals and quick fixes',
    category: 'SEO Tools',
    categorySlug: 'seo',
    icon: 'Gauge',
    slug: 'page-speed-checker',
    tags: ['new'],
    implemented: true,
    inputType: 'url',
    outputType: 'text',
  },
  {
    id: 'seo-audit',
    name: 'SEO Analyzer',
    description: 'Review on-page SEO basics, snippets, and structure',
    category: 'SEO Tools',
    categorySlug: 'seo',
    icon: 'SearchCheck',
    slug: 'seo-analyzer',
    tags: ['trending'],
    popular: true,
    implemented: true,
    inputType: 'url',
    outputType: 'text',
  },
  {
    id: 'seo-serp-preview',
    name: 'SERP Preview',
    description: 'Preview how your page title and description could appear in search',
    category: 'SEO Tools',
    categorySlug: 'seo',
    icon: 'MonitorSmartphone',
    slug: 'serp-preview',
    tags: ['new'],
    implemented: true,
    inputType: 'text',
    outputType: 'preview',
  },
  {
    id: 'seo-slug',
    name: 'URL Slug Generator',
    description: 'Turn a page title into a readable SEO-friendly slug',
    category: 'SEO Tools',
    categorySlug: 'seo',
    icon: 'TextCursorInput',
    slug: 'url-slug-generator',
    tags: ['new'],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },

  // ── CALCULATORS ────────────────────────────────────────────────────────────
  {
    id: 'age-calc',
    name: 'Age Calculator',
    description: 'Calculate exact age from date of birth',
    category: 'Calculators',
    categorySlug: 'calculator',
    icon: 'Calendar',
    slug: 'age-calculator',
    tags: ['trending'],
    popular: true,
    implemented: true,
    inputType: 'none',
    outputType: 'text',
  },
  {
    id: 'bmi-calc',
    name: 'BMI Calculator for Health Tracking',
    description: 'Calculate your Body Mass Index (BMI) for health tracking, fitness goals, and medical checks',
    category: 'Calculators',
    categorySlug: 'calculator',
    icon: 'Activity',
    slug: 'bmi-calculator',
    tags: [],
    popular: true,
    implemented: true,
    inputType: 'none',
    outputType: 'text',
  },
  {
    id: 'emi-calc',
    name: 'EMI Calculator for Loans',
    description: 'Calculate monthly loan EMI, interest rates, and repayment schedules for home or car loans',
    category: 'Calculators',
    categorySlug: 'calculator',
    icon: 'Banknote',
    slug: 'emi-calculator',
    tags: ['hot'],
    popular: true,
    implemented: true,
    inputType: 'none',
    outputType: 'text',
  },
  {
    id: 'currency-conv',
    name: 'Currency Converter',
    description: 'Convert between 170+ world currencies',
    category: 'Calculators',
    categorySlug: 'calculator',
    icon: 'DollarSign',
    slug: 'currency-converter',
    tags: ['trending'],
    popular: true,
    implemented: true,
    inputType: 'none',
    outputType: 'text',
  },
  {
    id: 'unit-conv',
    name: 'Unit Converter (Metric & Imperial)',
    description: 'Quickly convert units for length, weight, temperature, and volume across Metric and Imperial systems',
    category: 'Calculators',
    categorySlug: 'calculator',
    icon: 'Ruler',
    slug: 'unit-converter',
    tags: [],
    implemented: true,
    inputType: 'none',
    outputType: 'text',
  },
  {
    id: 'pct-calc',
    name: 'Percentage Calculator',
    description: 'Calculate percentages, discounts and more',
    category: 'Calculators',
    categorySlug: 'calculator',
    icon: 'Percent',
    slug: 'percentage-calculator',
    tags: [],
    implemented: true,
    inputType: 'none',
    outputType: 'text',
  },
  {
    id: 'compound-interest',
    name: 'Compound Interest',
    description: 'Calculate compound interest growth over time',
    category: 'Calculators',
    categorySlug: 'calculator',
    icon: 'TrendingUp',
    slug: 'compound-interest-calculator',
    tags: ['new'],
    implemented: true,
    inputType: 'none',
    outputType: 'text',
  },
  {
    id: 'gst-calc',
    name: 'GST Calculator',
    description: 'Calculate GST amount on products and services',
    category: 'Calculators',
    categorySlug: 'calculator',
    icon: 'Receipt',
    slug: 'gst-calculator',
    tags: ['new'],
    implemented: true,
    inputType: 'none',
    outputType: 'text',
  },
  {
    id: 'tip-calc',
    name: 'Tip Calculator',
    description: 'Calculate restaurant tip and split bills',
    category: 'Calculators',
    categorySlug: 'calculator',
    icon: 'Coffee',
    slug: 'tip-calculator',
    tags: [],
    implemented: true,
    inputType: 'none',
    outputType: 'text',
  },
  {
    id: 'date-diff',
    name: 'Date Difference',
    description: 'Calculate exact time between two dates',
    category: 'Calculators',
    categorySlug: 'calculator',
    icon: 'CalendarDays',
    slug: 'date-difference-calculator',
    tags: [],
    implemented: true,
    inputType: 'none',
    outputType: 'text',
  },
  {
    id: 'timezone-conv',
    name: 'Timezone Converter',
    description: 'Convert time across world time zones',
    category: 'Calculators',
    categorySlug: 'calculator',
    icon: 'Globe',
    slug: 'timezone-converter',
    tags: ['new'],
    implemented: true,
    inputType: 'none',
    outputType: 'text',
  },
  {
    id: 'calorie-calc',
    name: 'Calorie Calculator',
    description: 'Calculate daily calorie intake needs',
    category: 'Calculators',
    categorySlug: 'calculator',
    icon: 'Flame',
    slug: 'calorie-calculator',
    tags: ['beta'],
    implemented: true,
    inputType: 'none',
    outputType: 'text',
  },
  {
    id: 'salary-calc',
    name: 'Salary Calculator (Net Take-Home)',
    description: 'Calculate your net take-home salary after tax deductions and contributions instantly',
    category: 'Calculators',
    categorySlug: 'calculator',
    icon: 'Wallet',
    slug: 'salary-calculator',
    tags: ['new'],
    implemented: true,
    inputType: 'none',
    outputType: 'text',
  },

  // ── FILE TOOLS ─────────────────────────────────────────────────────────────
  {
    id: 'zip-creator',
    name: 'ZIP Creator',
    description: 'Compress files into ZIP archives',
    category: 'File Tools',
    categorySlug: 'file',
    icon: 'Archive',
    slug: 'zip-creator',
    tags: ['trending'],
    implemented: true,
    inputType: 'file',
    outputType: 'file',
  },
  {
    id: 'file-hash',
    name: 'File Hash Checker',
    description: 'Verify file integrity with MD5/SHA hashes',
    category: 'File Tools',
    categorySlug: 'file',
    icon: 'ShieldCheck',
    slug: 'file-hash-checker',
    tags: ['new'],
    implemented: true,
    inputType: 'file',
    outputType: 'text',
  },
  {
    id: 'file-metadata',
    name: 'File Metadata Viewer',
    description: 'View detailed metadata of any file',
    category: 'File Tools',
    categorySlug: 'file',
    icon: 'Info',
    slug: 'file-metadata-viewer',
    tags: [],
    implemented: true,
    inputType: 'file',
    outputType: 'text',
  },
  {
    id: 'binary-text',
    name: 'Binary to Text',
    description: 'Convert binary code to readable text',
    category: 'File Tools',
    categorySlug: 'file',
    icon: 'Binary',
    slug: 'binary-to-text',
    tags: [],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'text-binary',
    name: 'Text to Binary',
    description: 'Convert text to binary code',
    category: 'File Tools',
    categorySlug: 'file',
    icon: 'Code2',
    slug: 'text-to-binary',
    tags: [],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },

  // ── AI TOOLS ───────────────────────────────────────────────────────────────
  {
    id: 'ai-summarizer',
    name: 'AI Summarizer',
    description: 'Summarize long articles and documents with AI',
    category: 'AI Tools',
    categorySlug: 'ai',
    icon: 'Sparkles',
    slug: 'ai-summarizer',
    tags: ['hot', 'trending'],
    popular: true,
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'ai-paraphraser',
    name: 'AI Paraphraser',
    description: 'Rephrase content in different styles',
    category: 'AI Tools',
    categorySlug: 'ai',
    icon: 'RefreshCcw',
    slug: 'ai-paraphraser',
    tags: ['trending'],
    popular: true,
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'ai-grammar',
    name: 'Grammar Checker',
    description: 'AI-powered grammar and writing improvement',
    category: 'AI Tools',
    categorySlug: 'ai',
    icon: 'CheckCircle',
    slug: 'grammar-checker',
    tags: ['hot'],
    popular: true,
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'ai-translator',
    name: 'AI Translator',
    description: 'Translate text between 100+ languages',
    category: 'AI Tools',
    categorySlug: 'ai',
    icon: 'Languages',
    slug: 'ai-translator',
    tags: ['trending'],
    popular: true,
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'ai-code-gen',
    name: 'AI Code Generator',
    description: 'Generate code in any programming language',
    category: 'AI Tools',
    categorySlug: 'ai',
    icon: 'Terminal',
    slug: 'ai-code-generator',
    tags: ['hot', 'new'],
    popular: true,
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'ai-email',
    name: 'AI Email Writer',
    description: 'Write professional emails in seconds',
    category: 'AI Tools',
    categorySlug: 'ai',
    icon: 'Mail',
    slug: 'ai-email-writer',
    tags: ['new'],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'ai-seo-writer',
    name: 'AI SEO Writer',
    description: 'Write SEO-optimized blog posts and articles',
    category: 'AI Tools',
    categorySlug: 'ai',
    icon: 'PenLine',
    slug: 'ai-seo-writer',
    tags: ['new', 'beta'],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'ai-hashtag',
    name: 'Hashtag Generator',
    description: 'Generate trending hashtags for social media',
    category: 'AI Tools',
    categorySlug: 'ai',
    icon: 'Hash',
    slug: 'hashtag-generator',
    tags: ['trending'],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'ai-image-gen',
    name: 'AI Image Generator',
    description: 'Generate stunning images from text prompts',
    category: 'AI Tools',
    categorySlug: 'ai',
    icon: 'ImagePlus',
    slug: 'ai-image-generator',
    tags: ['hot', 'trending', 'new'],
    popular: true,
    implemented: true,
    inputType: 'text',
    outputType: 'file',
  },
  {
    id: 'ai-resume',
    name: 'AI Resume Builder',
    description: 'Create professional resumes with AI help',
    category: 'AI Tools',
    categorySlug: 'ai',
    icon: 'FileBadge2',
    slug: 'ai-resume-builder',
    tags: ['new'],
    implemented: true,
    inputType: 'text',
    outputType: 'file',
  },
  {
    id: 'ai-cover-letter',
    name: 'Cover Letter Writer',
    description: 'Write compelling cover letters with AI',
    category: 'AI Tools',
    categorySlug: 'ai',
    icon: 'ClipboardEdit',
    slug: 'ai-cover-letter',
    tags: ['new'],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },

  // ── NEW HIGH-TRAFFIC TOOLS ─────────────────────────────────────────────────

  // ── IMAGE TOOLS (High Traffic) ──
  {
    id: 'image-favicon-generator',
    name: 'Favicon Generator',
    description: 'Upload an image and generate .ico favicons for your website',
    category: 'Image Tools',
    categorySlug: 'image',
    icon: 'Globe',
    slug: 'favicon-generator',
    tags: ['new', 'trending'],
    popular: true,
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.png', '.jpg', '.jpeg', '.svg'],
  },
  {
    id: 'image-instagram-grid',
    name: 'Instagram Grid Maker',
    description: 'Split one image into 3, 6, or 9 grid tiles for Instagram',
    category: 'Image Tools',
    categorySlug: 'image',
    icon: 'Grid3x3',
    slug: 'instagram-grid-maker',
    tags: ['hot', 'new'],
    popular: true,
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.png', '.jpg', '.jpeg', '.webp'],
  },
  {
    id: 'image-svg-to-png',
    name: 'SVG to PNG Converter',
    description: 'Convert SVG vector files to high-quality PNG images',
    category: 'Image Tools',
    categorySlug: 'image',
    icon: 'FileImage',
    slug: 'svg-to-png',
    tags: ['new'],
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.svg'],
  },
  {
    id: 'image-meme-generator',
    name: 'Meme Generator',
    description: 'Add custom text to images and create viral memes instantly',
    category: 'Image Tools',
    categorySlug: 'image',
    icon: 'Laugh',
    slug: 'meme-generator',
    tags: ['hot', 'trending'],
    popular: true,
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.png', '.jpg', '.jpeg', '.webp'],
  },

  // ── VIDEO TOOLS (High Traffic) ──
  {
    id: 'video-tiktok-downloader',
    name: 'TikTok Video Downloader',
    description: 'Download public TikTok videos in a fast mobile-friendly downloader',
    category: 'Video Tools',
    categorySlug: 'video',
    icon: 'Music2',
    slug: 'tiktok-video-downloader',
    tags: ['hot', 'trending', 'new'],
    popular: true,
    implemented: true,
    inputType: 'url',
    outputType: 'file',
  },
  {
    id: 'video-instagram-downloader',
    name: 'Instagram Reels Downloader',
    description: 'Download Instagram Reels, Stories and posts in full quality',
    category: 'Video Tools',
    categorySlug: 'video',
    icon: 'Camera',
    slug: 'instagram-reels-downloader',
    tags: ['hot', 'new'],
    popular: true,
    implemented: true,
    inputType: 'url',
    outputType: 'file',
  },
  {
    id: 'video-instagram-video-downloader',
    name: 'Instagram Video Downloader',
    description: 'Download Instagram reels, posts, stories, highlights, and video links in one clean flow',
    category: 'Video Tools',
    categorySlug: 'video',
    icon: 'Instagram',
    slug: 'instagram-video-downloader',
    tags: ['hot', 'trending', 'new'],
    popular: true,
    implemented: true,
    inputType: 'url',
    outputType: 'file',
  },
  {
    id: 'video-instagram-story-downloader',
    name: 'Instagram Story Downloader',
    description: 'Save Instagram stories and highlights quickly with direct download options',
    category: 'Video Tools',
    categorySlug: 'video',
    icon: 'CirclePlay',
    slug: 'instagram-story-downloader',
    tags: ['new', 'trending'],
    popular: true,
    implemented: true,
    inputType: 'url',
    outputType: 'file',
  },
  {
    id: 'video-instagram-post-downloader',
    name: 'Instagram Post Downloader',
    description: 'Download public Instagram posts, videos, carousel media and image posts when accessible',
    category: 'Video Tools',
    categorySlug: 'video',
    icon: 'Images',
    slug: 'instagram-post-downloader',
    tags: ['new', 'trending'],
    popular: true,
    implemented: true,
    inputType: 'url',
    outputType: 'file',
  },
  {
    id: 'video-youtube-shorts',
    name: 'YouTube Shorts Downloader',
    description: 'Download YouTube Shorts videos to your device instantly',
    category: 'Video Tools',
    categorySlug: 'video',
    icon: 'Youtube',
    slug: 'youtube-shorts-downloader',
    tags: ['new', 'trending'],
    popular: true,
    implemented: true,
    inputType: 'url',
    outputType: 'file',
  },
  {
    id: 'video-youtube-playlist-downloader',
    name: 'YouTube Playlist Downloader',
    description: 'Analyze public YouTube playlists and download supported public media when available',
    category: 'Video Tools',
    categorySlug: 'video',
    icon: 'ListVideo',
    slug: 'youtube-playlist-downloader',
    tags: ['new', 'trending'],
    popular: true,
    implemented: true,
    inputType: 'url',
    outputType: 'file',
  },
  {
    id: 'video-youtube-downloader',
    name: 'YouTube Video Downloader',
    description: 'Download YouTube videos in MP4, MP3, WEBM, and thumbnail formats',
    category: 'Video Tools',
    categorySlug: 'video',
    icon: 'Youtube',
    slug: 'youtube-video-downloader',
    tags: ['hot', 'trending', 'new'],
    popular: true,
    implemented: true,
    inputType: 'url',
    outputType: 'file',
  },
  {
    id: 'video-facebook-downloader',
    name: 'Facebook Video Downloader',
    description: 'Download Facebook videos and reels in a fast mobile-friendly flow',
    category: 'Video Tools',
    categorySlug: 'video',
    icon: 'Facebook',
    slug: 'facebook-video-downloader',
    tags: ['new', 'trending'],
    popular: true,
    implemented: true,
    inputType: 'url',
    outputType: 'file',
  },
  {
    id: 'video-facebook-reels-downloader',
    name: 'Facebook Reels Downloader',
    description: 'Download public Facebook reels with a compact paste-and-save workflow',
    category: 'Video Tools',
    categorySlug: 'video',
    icon: 'Clapperboard',
    slug: 'facebook-reels-downloader',
    tags: ['new', 'trending'],
    popular: true,
    implemented: true,
    inputType: 'url',
    outputType: 'file',
  },
  {
    id: 'video-twitter-downloader',
    name: 'Twitter Video Downloader',
    description: 'Download Twitter and X videos from post URLs in a few taps',
    category: 'Video Tools',
    categorySlug: 'video',
    icon: 'Twitter',
    slug: 'twitter-video-downloader',
    tags: ['new', 'trending'],
    popular: true,
    implemented: true,
    inputType: 'url',
    outputType: 'file',
  },
  {
    id: 'video-pinterest-downloader',
    name: 'Pinterest Video Downloader',
    description: 'Download public Pinterest video pins, idea pins and image pins when accessible',
    category: 'Video Tools',
    categorySlug: 'video',
    icon: 'Pin',
    slug: 'pinterest-video-downloader',
    tags: ['new', 'trending'],
    popular: true,
    implemented: true,
    inputType: 'url',
    outputType: 'file',
  },
  {
    id: 'video-reddit-downloader',
    name: 'Reddit Video Downloader',
    description: 'Download public Reddit video posts, GIF posts and embedded public media',
    category: 'Video Tools',
    categorySlug: 'video',
    icon: 'MessageCircle',
    slug: 'reddit-video-downloader',
    tags: ['new', 'trending'],
    popular: true,
    implemented: true,
    inputType: 'url',
    outputType: 'file',
  },
  {
    id: 'video-vimeo-downloader',
    name: 'Vimeo Video Downloader',
    description: 'Save Vimeo videos with quick MP4, audio, and thumbnail downloads',
    category: 'Video Tools',
    categorySlug: 'video',
    icon: 'PlaySquare',
    slug: 'vimeo-video-downloader',
    tags: ['new'],
    popular: true,
    implemented: true,
    inputType: 'url',
    outputType: 'file',
  },
  {
    id: 'video-dailymotion-downloader',
    name: 'Dailymotion Video Downloader',
    description: 'Download Dailymotion videos in a compact no-clutter downloader workspace',
    category: 'Video Tools',
    categorySlug: 'video',
    icon: 'PlayCircle',
    slug: 'dailymotion-video-downloader',
    tags: ['new'],
    popular: true,
    implemented: true,
    inputType: 'url',
    outputType: 'file',
  },
  {
    id: 'video-snapchat-downloader',
    name: 'Snapchat Downloader',
    description: 'Download public Snapchat Spotlight and public story media when supported',
    category: 'Video Tools',
    categorySlug: 'video',
    icon: 'Ghost',
    slug: 'snapchat-downloader',
    tags: ['new'],
    popular: true,
    implemented: true,
    inputType: 'url',
    outputType: 'file',
  },
  {
    id: 'video-linkedin-downloader',
    name: 'LinkedIn Video Downloader',
    description: 'Download public LinkedIn video posts and accessible live recordings when supported',
    category: 'Video Tools',
    categorySlug: 'video',
    icon: 'Linkedin',
    slug: 'linkedin-video-downloader',
    tags: ['new', 'trending'],
    popular: true,
    implemented: true,
    inputType: 'url',
    outputType: 'file',
  },
  {
    id: 'video-telegram-downloader',
    name: 'Telegram Video Downloader',
    description: 'Download public Telegram channel videos and public media posts',
    category: 'Video Tools',
    categorySlug: 'video',
    icon: 'Send',
    slug: 'telegram-video-downloader',
    tags: ['new'],
    popular: true,
    implemented: true,
    inputType: 'url',
    outputType: 'file',
  },
  {
    id: 'video-twitch-clip-downloader',
    name: 'Twitch Clip Downloader',
    description: 'Download public Twitch clips, VODs and public streams when supported',
    category: 'Video Tools',
    categorySlug: 'video',
    icon: 'Twitch',
    slug: 'twitch-clip-downloader',
    tags: ['new', 'trending'],
    popular: true,
    implemented: true,
    inputType: 'url',
    outputType: 'file',
  },
  {
    id: 'video-bilibili-downloader',
    name: 'Bilibili Downloader',
    description: 'Download public Bilibili videos and supported public streams',
    category: 'Video Tools',
    categorySlug: 'video',
    icon: 'Tv',
    slug: 'bilibili-downloader',
    tags: ['new'],
    popular: true,
    implemented: true,
    inputType: 'url',
    outputType: 'file',
  },
  {
    id: 'video-likee-downloader',
    name: 'Likee Video Downloader',
    description: 'Download public Likee short videos with quick metadata detection',
    category: 'Video Tools',
    categorySlug: 'video',
    icon: 'Heart',
    slug: 'likee-video-downloader',
    tags: ['new'],
    popular: true,
    implemented: true,
    inputType: 'url',
    outputType: 'file',
  },
  {
    id: 'video-mxtakatak-downloader',
    name: 'MX TakaTak Downloader',
    description: 'Download public MX TakaTak short videos when source media is available',
    category: 'Video Tools',
    categorySlug: 'video',
    icon: 'Music',
    slug: 'mxtakatak-downloader',
    tags: ['new'],
    popular: true,
    implemented: true,
    inputType: 'url',
    outputType: 'file',
  },
  {
    id: 'video-sharechat-downloader',
    name: 'ShareChat Video Downloader',
    description: 'Download public ShareChat videos and Moj short videos when accessible',
    category: 'Video Tools',
    categorySlug: 'video',
    icon: 'Share2',
    slug: 'sharechat-video-downloader',
    tags: ['new'],
    popular: true,
    implemented: true,
    inputType: 'url',
    outputType: 'file',
  },
  {
    id: 'video-roposo-downloader',
    name: 'Roposo Video Downloader',
    description: 'Download public Roposo short videos in a clean mobile-friendly downloader',
    category: 'Video Tools',
    categorySlug: 'video',
    icon: 'Play',
    slug: 'roposo-video-downloader',
    tags: ['new'],
    popular: true,
    implemented: true,
    inputType: 'url',
    outputType: 'file',
  },
  {
    id: 'video-triller-downloader',
    name: 'Triller Video Downloader',
    description: 'Download public Triller short videos with direct save actions',
    category: 'Video Tools',
    categorySlug: 'video',
    icon: 'Clapperboard',
    slug: 'triller-video-downloader',
    tags: ['new'],
    popular: true,
    implemented: true,
    inputType: 'url',
    outputType: 'file',
  },
  {
    id: 'video-screen-recorder',
    name: 'Online Screen Recorder',
    description: 'Record your screen, camera, or both directly in the browser',
    category: 'Video Tools',
    categorySlug: 'video',
    icon: 'MonitorPlay',
    slug: 'screen-recorder',
    tags: ['new', 'hot'],
    popular: true,
    implemented: true,
    inputType: 'none',
    outputType: 'file',
  },

  // ── TEXT TOOLS (High Traffic) ──
  {
    id: 'text-password-generator',
    name: 'Password Generator',
    description: 'Generate strong, secure random passwords with custom settings',
    category: 'Text Tools',
    categorySlug: 'text',
    icon: 'KeyRound',
    slug: 'password-generator',
    tags: ['hot', 'trending'],
    popular: true,
    implemented: true,
    inputType: 'none',
    outputType: 'text',
  },
  {
    id: 'text-emoji-picker',
    name: 'Emoji Copy Paste',
    description: 'Browse, search, and copy any emoji with one click',
    category: 'Text Tools',
    categorySlug: 'text',
    icon: 'Smile',
    slug: 'emoji-copy-paste',
    tags: ['trending'],
    popular: true,
    implemented: true,
    inputType: 'none',
    outputType: 'text',
  },
  {
    id: 'text-fancy-font',
    name: 'Fancy Text Generator',
    description: 'Convert normal text into stylish, fancy Unicode fonts for social media',
    category: 'Text Tools',
    categorySlug: 'text',
    icon: 'Sparkles',
    slug: 'fancy-text-generator',
    tags: ['hot', 'new'],
    popular: true,
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'text-random-name',
    name: 'Random Name Picker / Wheel Spinner',
    description: 'Spin a wheel or pick random names from a list for giveaways',
    category: 'Text Tools',
    categorySlug: 'text',
    icon: 'Dices',
    slug: 'random-name-picker',
    tags: ['hot', 'trending'],
    popular: true,
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },

  // ── DEV TOOLS (High Traffic) ──
  {
    id: 'dev-css-gradient',
    name: 'CSS Gradient Generator',
    description: 'Create beautiful CSS gradients with a visual editor',
    category: 'Dev Tools',
    categorySlug: 'dev',
    icon: 'Paintbrush',
    slug: 'css-gradient-generator',
    tags: ['new', 'trending'],
    popular: true,
    implemented: true,
    inputType: 'none',
    outputType: 'text',
  },
  {
    id: 'dev-html-to-markdown',
    name: 'HTML to Markdown',
    description: 'Convert HTML code to clean Markdown format instantly',
    category: 'Dev Tools',
    categorySlug: 'dev',
    icon: 'FileCode',
    slug: 'html-to-markdown',
    tags: ['new'],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'dev-json-to-csv',
    name: 'JSON to CSV Converter',
    description: 'Transform JSON data into downloadable CSV spreadsheets',
    category: 'Dev Tools',
    categorySlug: 'dev',
    icon: 'Table',
    slug: 'json-to-csv-converter',
    tags: ['new', 'trending'],
    implemented: true,
    inputType: 'text',
    outputType: 'file',
  },
  {
    id: 'dev-cron-expression',
    name: 'Cron Expression Generator',
    description: 'Build and test cron expressions with a visual scheduler',
    category: 'Dev Tools',
    categorySlug: 'dev',
    icon: 'Clock',
    slug: 'cron-expression-generator',
    tags: ['new'],
    implemented: true,
    inputType: 'none',
    outputType: 'text',
  },
  {
    id: 'dev-markdown-preview',
    name: 'Markdown Previewer',
    description: 'Write Markdown and preview the rendered output in real time',
    category: 'Dev Tools',
    categorySlug: 'dev',
    icon: 'Eye',
    slug: 'markdown-previewer',
    tags: ['new'],
    implemented: true,
    inputType: 'text',
    outputType: 'preview',
  },
  {
    id: 'dev-yaml-to-json',
    name: 'YAML to JSON Converter',
    description: 'Convert simple YAML key-value data into clean JSON instantly',
    category: 'Dev Tools',
    categorySlug: 'dev',
    icon: 'FileCode',
    slug: 'yaml-to-json-converter',
    tags: ['new'],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'dev-xml-to-json',
    name: 'XML to JSON Converter',
    description: 'Convert XML markup into a readable JSON structure for quick debugging',
    category: 'Dev Tools',
    categorySlug: 'dev',
    icon: 'FileCode',
    slug: 'xml-to-json-converter',
    tags: ['new'],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'dev-timestamp-converter',
    name: 'Timestamp Converter',
    description: 'Convert Unix timestamps, ISO dates, and local time values quickly',
    category: 'Dev Tools',
    categorySlug: 'dev',
    icon: 'Timer',
    slug: 'timestamp-converter',
    tags: ['new', 'trending'],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },

  // ── SEO TOOLS (High Traffic) ──
  {
    id: 'seo-og-image',
    name: 'Open Graph Image Generator',
    description: 'Generate beautiful OG images for social media sharing',
    category: 'SEO Tools',
    categorySlug: 'seo',
    icon: 'Image',
    slug: 'og-image-generator',
    tags: ['new', 'trending'],
    popular: true,
    implemented: true,
    inputType: 'text',
    outputType: 'file',
  },
  {
    id: 'seo-schema-generator',
    name: 'Schema Markup Generator',
    description: 'Generate JSON-LD structured data for rich Google search results',
    category: 'SEO Tools',
    categorySlug: 'seo',
    icon: 'Code',
    slug: 'schema-markup-generator',
    tags: ['new'],
    implemented: true,
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 'seo-redirect-checker',
    name: 'Redirect Chain Checker',
    description: 'Check URL redirect chains and identify 301/302 hops',
    category: 'SEO Tools',
    categorySlug: 'seo',
    icon: 'ArrowRightLeft',
    slug: 'redirect-checker',
    tags: ['new'],
    implemented: true,
    inputType: 'url',
    outputType: 'text',
  },

  // ── CALCULATOR TOOLS (High Traffic) ──
  {
    id: 'calc-discount',
    name: 'Discount Calculator',
    description: 'Calculate sale prices and total savings with percentage discounts',
    category: 'Calculators',
    categorySlug: 'calculator',
    icon: 'BadgePercent',
    slug: 'discount-calculator',
    tags: ['hot', 'trending'],
    popular: true,
    implemented: true,
    inputType: 'none',
    outputType: 'text',
  },
  {
    id: 'calc-aspect-ratio',
    name: 'Aspect Ratio Calculator',
    description: 'Calculate and maintain aspect ratios for images and video',
    category: 'Calculators',
    categorySlug: 'calculator',
    icon: 'RatioIcon',
    slug: 'aspect-ratio-calculator',
    tags: ['new'],
    implemented: true,
    inputType: 'none',
    outputType: 'text',
  },
  {
    id: 'calc-gpa',
    name: 'GPA Calculator',
    description: 'Calculate your GPA and CGPA from grades and credit hours',
    category: 'Calculators',
    categorySlug: 'calculator',
    icon: 'GraduationCap',
    slug: 'gpa-calculator',
    tags: ['new', 'trending'],
    popular: true,
    implemented: true,
    inputType: 'none',
    outputType: 'text',
  },
  {
    id: 'calc-loan',
    name: 'Loan / Mortgage Calculator',
    description: 'Estimate monthly payments and total interest for any loan',
    category: 'Calculators',
    categorySlug: 'calculator',
    icon: 'Landmark',
    slug: 'loan-calculator',
    tags: ['new'],
    implemented: true,
    inputType: 'none',
    outputType: 'text',
  },
  {
    id: 'calc-stopwatch',
    name: 'Online Stopwatch & Timer',
    description: 'Precise stopwatch and countdown timer right in your browser',
    category: 'Calculators',
    categorySlug: 'calculator',
    icon: 'Timer',
    slug: 'online-stopwatch',
    tags: ['hot', 'trending'],
    popular: true,
    implemented: true,
    inputType: 'none',
    outputType: 'text',
  },

  // ── FILE TOOLS (High Traffic) ──
  {
    id: 'file-zip-extractor',
    name: 'ZIP Extractor',
    description: 'Extract and view files from ZIP archives online',
    category: 'File Tools',
    categorySlug: 'file',
    icon: 'FolderOpen',
    slug: 'zip-extractor',
    tags: ['new', 'trending'],
    popular: true,
    implemented: true,
    inputType: 'file',
    outputType: 'file',
    acceptedFormats: ['.zip'],
  },
  {
    id: 'file-csv-viewer',
    name: 'CSV Viewer & Editor',
    description: 'Open, view, and edit CSV files in a clean spreadsheet UI',
    category: 'File Tools',
    categorySlug: 'file',
    icon: 'Sheet',
    slug: 'csv-viewer',
    tags: ['new'],
    implemented: true,
    inputType: 'file',
    outputType: 'preview',
    acceptedFormats: ['.csv'],
  },
  {
    id: 'file-json-viewer',
    name: 'JSON File Viewer',
    description: 'Open and visualize JSON files with syntax highlighting',
    category: 'File Tools',
    categorySlug: 'file',
    icon: 'FileJson',
    slug: 'json-file-viewer',
    tags: ['new'],
    implemented: true,
    inputType: 'file',
    outputType: 'preview',
    acceptedFormats: ['.json'],
  },
]

const CATEGORY_ALLOWED_SLUGS: Partial<Record<string, Set<string>>> = {
  audio: new Set([
    'compress-audio',
    'audio-recorder',
    'bpm-detector',
    'convert-audio',
    'trim-audio',
    'audio-equalizer',
    'audio-metadata-editor',
    'speech-to-text',
    'change-audio-speed',
    'merge-audio',
    'remove-vocals',
    'audio-text-to-speech',
    'trim-silence',
    'volume-booster',
  ]),
  text: new Set([
    'ai-text-generator',
    'word-counter',
    'text-case-converter',
    'remove-duplicate-lines',
    'text-reverser',
    'text-grammar-checker',
    'paraphrasing-tool',
    'plagiarism-checker',
    'text-speech-to-text',
    'text-diff-checker',
    'text-summarizer',
    'text-to-speech',
    'text-url-encoder-decoder',
    'password-generator',
    'lorem-ipsum-generator',
    'emoji-copy-paste',
    'fancy-text-generator',
    'random-name-picker',
    'markdown-to-html',
    'csv-to-json',
    'json-to-csv',
    'string-extractor',
    'readability-score',
    'keyword-density',
  ]),
  dev: new Set([
    'api-tester',
    'base64-encoder-decoder',
    'code-formatter',
    'color-converter',
    'css-minifier',
    'cron-generator',
    'gradient-generator',
    'gitignore-generator',
    'hash-generator',
    'html-previewer',
    'json-formatter',
    'jwt-decoder',
    'js-minifier',
    'regex-tester',
    'sql-formatter',
    'url-encoder-decoder',
    'uuid-generator',
    'css-gradient-generator',
    'html-to-markdown',
    'json-to-csv-converter',
    'cron-expression-generator',
    'markdown-previewer',
    'yaml-to-json-converter',
    'xml-to-json-converter',
    'timestamp-converter',
  ]),
  seo: new Set([
    'backlink-checker',
    'broken-link-checker',
    'domain-authority-checker',
    'image-seo-checker',
    'keyword-generator',
    'meta-tag-generator',
    'open-graph-generator',
    'page-speed-checker',
    'robots-txt-generator',
    'seo-analyzer',
    'serp-preview',
    'sitemap-generator',
    'url-slug-generator',
    'og-image-generator',
    'schema-markup-generator',
    'redirect-checker',
    'keyword-extractor',
    'social-media-preview',
  ]),
  calculator: new Set([
    'age-calculator',
    'bmi-calculator',
    'emi-calculator',
    'currency-converter',
    'unit-converter',
    'percentage-calculator',
    'compound-interest-calculator',
    'gst-calculator',
    'tip-calculator',
    'date-difference-calculator',
    'timezone-converter',
    'calorie-calculator',
    'discount-calculator',
    'aspect-ratio-calculator',
    'gpa-calculator',
    'loan-calculator',
    'online-stopwatch',
    'salary-calculator',
  ]),
}

function isAllowedCategoryTool(tool: Tool) {
  if (DISABLED_PUBLIC_TOOL_SLUGS.has(tool.slug)) return false

  const allowed = CATEGORY_ALLOWED_SLUGS[tool.categorySlug]
  return allowed ? allowed.has(tool.slug) : true
}

export const DISABLED_PUBLIC_TOOL_SLUGS = new Set([
  'youtube-shorts-downloader',
  'youtube-playlist-downloader',
  'youtube-video-downloader',
])

const ACTIVE_TOOL_SLUGS = new Set(
  ALL_TOOLS.filter(tool => tool.implemented && isAllowedCategoryTool(tool)).map(tool => tool.slug)
)

export const VIDEO_DOWNLOADER_TOOL_SLUGS = new Set([
  'all-in-one-video-downloader',
  'tiktok-video-downloader',
  'instagram-reels-downloader',
  'instagram-video-downloader',
  'instagram-story-downloader',
  'instagram-post-downloader',
  'facebook-video-downloader',
  'facebook-reels-downloader',
  'twitter-video-downloader',
  'pinterest-video-downloader',
  'reddit-video-downloader',
  'vimeo-video-downloader',
  'dailymotion-video-downloader',
  'snapchat-downloader',
  'linkedin-video-downloader',
  'telegram-video-downloader',
  'twitch-clip-downloader',
  'bilibili-downloader',
  'likee-video-downloader',
  'mxtakatak-downloader',
  'sharechat-video-downloader',
  'roposo-video-downloader',
  'triller-video-downloader',
])

export const TOOL_SLUG_ALIASES: Record<string, string> = {
  'video-downloader': 'all-in-one-video-downloader',
  'online-video-downloader': 'all-in-one-video-downloader',
  'instagram-downloader': 'instagram-video-downloader',
  'instagram-posts-downloader': 'instagram-post-downloader',
  'instagram-stories-downloader': 'instagram-story-downloader',
  'instagram-highlights-downloader': 'instagram-story-downloader',
  'instagram-highlight-downloader': 'instagram-story-downloader',
  'reels-downloader': 'instagram-reels-downloader',
  'instagram-reel-downloader': 'instagram-reels-downloader',
  'facebook-downloader': 'facebook-video-downloader',
  'fb-video-downloader': 'facebook-video-downloader',
  'facebook-reel-downloader': 'facebook-reels-downloader',
  'fb-reels-downloader': 'facebook-reels-downloader',
  'tiktok-downloader': 'tiktok-video-downloader',
  'twitter-downloader': 'twitter-video-downloader',
  'twitter-x-video-downloader': 'twitter-video-downloader',
  'x-video-downloader': 'twitter-video-downloader',
  'pinterest-downloader': 'pinterest-video-downloader',
  'reddit-downloader': 'reddit-video-downloader',
  'vimeo-downloader': 'vimeo-video-downloader',
  'dailymotion-downloader': 'dailymotion-video-downloader',
  'linkedin-downloader': 'linkedin-video-downloader',
  'telegram-downloader': 'telegram-video-downloader',
  'twitch-downloader': 'twitch-clip-downloader',
  'twitch-vod-downloader': 'twitch-clip-downloader',
  'likee-downloader': 'likee-video-downloader',
  'sharechat-downloader': 'sharechat-video-downloader',
  'moj-video-downloader': 'sharechat-video-downloader',
  'roposo-downloader': 'roposo-video-downloader',
  'triller-downloader': 'triller-video-downloader',
}

export function resolveToolSlug(slug: string): string {
  return TOOL_SLUG_ALIASES[slug] || slug
}

export const TOOLS: Tool[] = ALL_TOOLS.filter(tool => ACTIVE_TOOL_SLUGS.has(tool.slug) && isAllowedCategoryTool(tool))
export const ACTIVE_CATEGORIES = CATEGORIES.filter(category => TOOLS.some(tool => tool.categorySlug === category.slug))

export const TRENDING_TOOLS = [
  ...TOOLS.filter(t => t.slug === 'all-in-one-video-downloader'),
  ...TOOLS.filter(t => (t.tags.includes('trending') || t.popular) && t.slug !== 'all-in-one-video-downloader'),
].slice(0, 12)
export const NEW_TOOLS = TOOLS.filter(t => t.tags.includes('new')).slice(0, 12)

export function getToolsByCategory(slug: string): Tool[] {
  return TOOLS.filter(t => t.categorySlug === slug)
}

export function getToolBySlug(slug: string): Tool | undefined {
  return TOOLS.find(t => t.slug === slug)
}

export function searchTools(query: string): Tool[] {
  const q = query.toLowerCase()
  return TOOLS.filter(
    t =>
      t.name.toLowerCase().includes(q) ||
      t.description.toLowerCase().includes(q) ||
      t.category.toLowerCase().includes(q)
  )
}
